## numpy 연습문제

url = 'https://www.machinelearningplus.com/python/101-numpy-exercises-python/'

In [ ]:
#1 ~ 5

#2.How to create a 1D array?
# Difficulty Level: L1 Q. Create a 1D array of numbers from 0 to 9 Desired output:
#> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#3. How to create a boolean array?
# Difficulty Level: L1 Q. Create a 3×3 numpy array of all True’s

#4. How to extract items that satisfy a given condition from 1D array?
# Difficulty Level: L1 Q. Extract all odd numbers from arr Input:
#         arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# Desired output:

#> array([1, 3, 5, 7, 9])

# 5. How to replace items that satisfy a condition with another value in numpy array?
# Difficulty Level: L1 Q. Replace all odd numbers in arr with -1 Input:

# arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# Desired Output:

# #>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])


In [ ]:
# 1. Import numpy as np and see the version
# Difficulty Level: L1 Q. Import numpy as `np` and print the version number

In [2]:
import numpy as np
print(np.__version__)

1.20.3


In [ ]:
# 2. How to create a 1D array?
# Difficulty Level: L1 Q. Create a 1D array of numbers from 0 to 9 Desired output:

#> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.array(np.arange(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# 3. How to create a boolean array?
# Difficulty Level: L1 Q. Create a 3×3 numpy array of all True’s

In [7]:
#1
np.full((3,3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [9]:
#2
np.ones((3,3), dtype= bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [10]:
# 4. How to extract items that satisfy a given condition from 1D array?
# Difficulty Level: L1 Q. Extract all odd numbers from arr Input:
#         arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# Desired output:

# #> array([1, 3, 5, 7, 9])

In [14]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[ arr%2 ==1 ]

array([1, 3, 5, 7, 9])

In [ ]:
# 5. How to replace items that satisfy a condition with another value in numpy array?
# Difficulty Level: L1 Q. Replace all odd numbers in arr with -1 Input:

# arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# Desired Output:

# #>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [16]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2 ==1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [ ]:
# 6~10

# 6. How to replace items that satisfy a condition without affecting the original array?
# Difficulty Level: L2 Q. Replace all odd numbers in arr with -1 without changing arr Input
# arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# Desired Output:

# out
#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
# arr
#>  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 7. How to reshape an array?
# Difficulty Level: L1 Q. Convert a 1D array to a 2D array with 2 rows Input:
# np.arange(10)
#> array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Desired Output:
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9]])

# 8. How to stack two arrays vertically?
# Difficulty Level: L2 Q. Stack arrays a and b vertically Input

# a = np.arange(10).reshape(2,-1)
# b = np.repeat(1, 10).reshape(2,-1)
# Desired Output:

    #> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9],
#>        [1, 1, 1, 1, 1],
#>        [1, 1, 1, 1, 1]])

# 9. How to stack two arrays horizontally?
# Difficulty Level: L2 Q. Stack the arrays a and b horizontally. Input
# 행렬 가로로 붙이기

# a = np.arange(10).reshape(2,-1)
# b = np.repeat(1, 10).reshape(2,-1)
# Desired Output:

#> array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
#>        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

# 10. How to generate custom sequences in numpy without hardcoding?
# Difficulty Level: L2 Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a. Input:

a = np.array([1,2,3])
# Desired Output:

#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [ ]:
# 6. How to replace items that satisfy a condition without affecting the original array?
# Difficulty Level: L2 Q. Replace all odd numbers in arr with -1 without changing arr Input

# arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# Desired Output:

# out
# #>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
# arr
# #>  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arr = np.arange(10)
out = np.where(arr%2 ==1, -1, arr)
print(arr)
print(out)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [ ]:
# 7. How to reshape an array?
# Difficulty Level: L1 Q. Convert a 1D array to a 2D array with 2 rows Input:

# np.arange(10)

# #> array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# Desired Output:

# #> array([[0, 1, 2, 3, 4],
# #>        [5, 6, 7, 8, 9]])

In [20]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [21]:
# 8. How to stack two arrays vertically?
# Difficulty Level: L2 Q. Stack arrays a and b vertically Input

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
# Desired Output:

    #> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9],
#>        [1, 1, 1, 1, 1],
#>        [1, 1, 1, 1, 1]])

In [23]:
#3가지 방법
#1. 
np.concatenate([a,b], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [24]:
#2.
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [25]:
#3.
np.r_[a,b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [26]:
# 9. How to stack two arrays horizontally?
# Difficulty Level: L2 Q. Stack the arrays a and b horizontally. Input
# 행렬 가로로 붙이기

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
# Desired Output:

#> array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
#>        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [29]:
np.arange(10).reshape(2,-1)  # reshape(2,-1)에서 -1의 의미: 2행으로 열은 나머지로 알아서 맞춰라 

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [30]:
#1.
np.concatenate([a,b],axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [32]:
#2.
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [35]:
np.c_[a,b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [37]:
# 10. How to generate custom sequences in numpy without hardcoding?
# Difficulty Level: L2 Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a. Input:

a = np.array([1,2,3])
# Desired Output:

#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [39]:
np.r_[np.repeat(a,3), np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [40]:
# 11. How to get the common items between two python numpy arrays?
# Difficulty Level: L2 Q. Get the common items between a and b Input:

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
# Desired Output:

# array([2, 4])

In [42]:
np.intersect1d(a,b)

array([2, 4])

In [44]:
# 12. How to remove from one array those items that exist in another?
# Difficulty Level: L2 Q. From array a remove all items present in array b Input:

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
# Desired Output:

# array([1,2,3,4])

In [45]:
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [48]:
# 13. How to get the positions where elements of two arrays match?
# Difficulty Level: L2 Q. Get the positions where elements of a and b match Input:

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
# Desired Output:
    #> (array([1, 3, 5, 7]),)

In [50]:
np.where(a==b)  # 인덱스 출력

(array([1, 3, 5, 7], dtype=int64),)

In [51]:
# 14. How to extract all numbers between a given range from a numpy array?
# Difficulty Level: L2 Q. Get all items between 5 and 10 from a. Input:

a = np.array([2, 6, 1, 9, 10, 3, 27])
# Desired Output:

# (array([6, 9, 10]),)

In [55]:
#1
index = np.where((a>=5) & (a<=10))  # 인덱스 출력
a[index]

array([ 6,  9, 10])

In [57]:
#2
a[(a>=5) & (a <= 10)]

array([ 6,  9, 10])

In [58]:
# 15. How to make a python function that handles scalars to work on numpy arrays?
# Difficulty Level: L2 Q. Convert the function maxx that works on two scalars, to work on two arrays. Input:

# def maxx(x, y):
#     """Get the maximum of two items"""
#     if x >= y:
#         return x
#     else:
#         return y

# maxx(1, 5)
# #> 5
# Desired Output:

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
# pair_max(a, b)
# #> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

In [64]:
# 16. How to swap two columns in a 2d numpy array?
# Difficulty Level: L2 Q. Swap columns 1 and 2 in the array arr.

arr = np.arange(9).reshape(3,3)
# arr
arr[:,[1,0,2]]  # why??????? 일단 외우자

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [67]:
# 17. How to swap two rows in a 2d numpy array?
# Difficulty Level: L2 Q. Swap rows 1 and 2 in the array arr:

arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [69]:
arr[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [72]:
# 18. How to reverse the rows of a 2D array?
# Difficulty Level: L2 Q. Reverse the rows of a 2D array arr.

## Input
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [73]:
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [74]:
# 19. How to reverse the columns of a 2D array?
# Difficulty Level: L2 Q. Reverse the columns of a 2D array arr.

# # Input
arr = np.arange(9).reshape(3,3)

In [77]:
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [79]:
# 20. How to create a 2D array containing random floats between 5 and 10?
# Difficulty Level: L2 Q. Create a 2D array of shape 5×3 to contain random decimal numbers between 5 and 10

In [86]:
#1
rand_arr = np.random.randint(low=5, high=10, size=(5,3))+ np.random.random((5,3))  # 정수 부분 + 소수부분 좋은방법인가..?
rand_arr

array([[5.4984547 , 6.75900131, 9.80286841],
       [8.76574901, 5.74795246, 6.34420876],
       [7.30914311, 6.77907916, 8.1148131 ],
       [6.00246531, 6.75889802, 6.37412172],
       [5.70458179, 9.42360685, 8.89524858]])

In [89]:
#2. 
rand_arr = np.random.uniform(5,10, size=(5,3))
rand_arr

array([[8.34038272, 9.3503205 , 6.14276949],
       [6.43631772, 8.42130191, 6.57222254],
       [6.25174847, 6.00456483, 6.22570243],
       [7.55032495, 6.86373763, 7.37703907],
       [5.91130131, 5.68813125, 8.96967003]])