# 뉴스 분류하기

In [229]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [56]:
from konlpy.tag import Hannanum, Komoran, Kkma, Twitter
from sklearn.cluster import AgglomerativeClustering, kmeans_plusplus, DBSCAN
import scipy.cluster.hierarchy as shc
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer

In [4]:
han = Hannanum()

In [7]:
data = pd.read_excel('../data/clustering_data.xlsx')
data

검색어  \
0                                    유한양행   
1                                    유한양행   
2                                    유한양행   
3                                    유한양행   
4                                    유한양행   
5                                      라돈   
6                                      라돈   
7                                      라돈   
8                                      라돈   
9                                      라돈   
10                               복면가왕 왕밤빵   
11                               복면가왕 왕밤빵   
12                               복면가왕 왕밤빵   
13                               복면가왕 왕밤빵   
14  복면가왕 왕밤빵15:15B1213:1614:1613:16B11:16   

                                                 기사내용  
0   유한양행은 얀센 바이오테크(Janssen Biotech Inc)와 EGFR표적 항암...  
1   유한양행이 1조4000억원 규모의 기술이전 계약 체결 소식에 가격제한폭까지 치솟았다...  
2   유한양행이 다국적 제약사 얀센에 기술수출했다는 소식에 주가가 5일 장 초반 상한가를...  
3   유한양행은 얀센 바이오테크((Janssen Biotech, Inc.)와 EGFR(상...  
4   유한양행이 1조4000억원 규모 기술 수출 소식에 가격제한폭까지 치솟았다. 유한양행...  
5   최근 침대 매트리스에 이어 온수매트에서도 라돈이 검출됐다는 소식이 알려지면서, 가정...  
6    침대, 생리대, 마스크 등에서 라돈이 검출되면서, 발암 물질 ‘라돈’에 대한 관심...  
7   하이젠 온수매트가 '라돈 온수매트'로 언급되고 있다.\n최근 한 온라인커뮤니티에서는...  
8   겨울 난방 제품인 온수매트에서 라돈이 검출된 가운데 해당 업체가 별 문제가 되지 않...  
9   매트리스, 생리대에 이어 온수 매트에서도 라돈이 검출돼 이슈로 떠올랐다.\n5일 오...  
10  복면가왕’ 88대 가왕 자리는 2연승의 왕밤빵이 차지했다.\n4일 오후 방송된 MB...  
11  복면가왕'에 출연해 왕밤빵에 패하면서 얼굴을 공개한 '축음기' 천단비에 관심이 쏠리...  
12  지난 4일 방송된 MBC ‘복면가왕’에서는 왕밤빵에 맞서 축음기, 조커, 북극곰 버...  
13  복면가왕' 왕밤빵의 정체가 더욱더 오리무중에 빠졌다. \n4일 방송된 MBC 예능프...  
14  복면가왕' 왕밤빵이 첫 방어전에 성공하며 2연승을 차지했다.\n지난 4일 방송된 M...

In [8]:
# 12행 뉴스
data.iloc[11,1]

'복면가왕\'에 출연해 왕밤빵에 패하면서 얼굴을 공개한 \'축음기\' 천단비에 관심이 쏠리고 있다.\n지난 4일 방송된 MBC 예능프로그램 \'복면가왕\'에서는 왕밤빵과 축음기가 88대 가왕 자리를 놓고 대결을 벌였다. 그 결과 왕밤빵이 가왕에 올랐다.\n이날 축음기는 박정현의 \'미아\'로 남다른 가창력을 자랑했지만 왕밤빵에 패하고 말았다. 이에 축음기는 가면을 벗었고, 드러난 정체는 바로 가수 천단비였다.\n천단비는 방송이 끝난 후 자신의 인스타그램을 통해 "제게 노래하는 무대가 소중하지 않은 순간이 있겠냐마는 유독 또 소중하고 행복한 순간이 하나 더 생겼다. 열심히 더 노래하겠다"고 \'복면가왕\' 출연 소감을 전했다.\n천단비는 2015년 Mnet \'슈퍼스타K7\'에 출연하며 주목받았지만 데뷔는 훨씬 빨랐다. 2005년 SBS \'건빵선생과 별사탕\' OST \'눈물샘\'으로 데뷔한 바 있다.\n\'슈스케7\' 준우승 후 각종 OST에 참여하며 노래를 불러온 천단비는 지난해  \'어느 봄의 거짓말\'을 발매해 많은 팬들의 사랑을 받기도 했다.'

In [9]:
 # 유사한 텍스트끼리 묶는다

In [22]:
kor = Komoran()

docs = []

for news in data['기사내용']:
    docs.append(kor.nouns(news))

In [23]:
docs

[['유한양행',
  '얀센',
  '바이오',
  '테크',
  '표적',
  '항암',
  '치료제',
  '기술이전',
  '계약',
  '체결',
  '일',
  '공시',
  '기술',
  '수출',
  '금액',
  '달러',
  '한화',
  '원',
  '계약금',
  '달러',
  '개발',
  '허가',
  '매출',
  '단계',
  '마일스톤',
  '달러',
  '수령',
  '예정',
  '순',
  '매출액',
  '책정',
  '유한양행',
  '관계자',
  '기술이전',
  '계약',
  '수익',
  '인식',
  '임상시험',
  '허가',
  '등',
  '성공',
  '여부',
  '수',
  '미',
  '실현',
  '있다'],
 ['유한양행',
  '원',
  '규모',
  '기술이전',
  '계약',
  '체결',
  '소식',
  '가격제한폭',
  '일',
  '오전',
  '시',
  '3분',
  '유한양행',
  '전날',
  '원',
  '원',
  '거래',
  '사흘',
  '연속',
  '강세',
  '유한양행',
  '글로벌',
  '약사',
  '존슨',
  '앤',
  '존슨',
  'J&J',
  '자회사',
  '얀센',
  '바이오',
  '테크',
  '해제',
  '기술',
  '수출',
  '계약',
  '체결',
  '이날',
  '계약',
  '규모',
  '원',
  '달러',
  '반환',
  '의무',
  '계약금',
  '원',
  '달러',
  '이번',
  '계약',
  '얀센',
  '전',
  '세계',
  '개발',
  '제조',
  '상업',
  '독점',
  '권리',
  '국내',
  '개발',
  '상업',
  '권리',
  '유한양행',
  '유지',
  '유한양행',
  '얀센',
  '바',
  '이',
  '오텍',
  '내년',
  '단일',
  '요법',
  '병용',
  '요법',
  '글로벌',
  '임상시험',
  '공동',
  '진행',


## 단어를 숫자로 전환

### 1. counter vectorizing

        형태소1, 형태소2, 형태소3, 형태소4 ...
문서1     0        2        1        0   =>  (0,2,1,0  ...)<br>
문서2     1        1        0        0           =>  (1,1,0,0, ...)<br>
문서3     0        0        3        0           =>  (0,0,3,0, ...)<br>
...

### 2. tfidf vectorizing

문서에서 형태소1 등장수 : tf<br>
전체 문서에서 형태소1이 등장한 문서수 : idf<br>
tfidf = tf/idf => 특정 형태소가 특정 문서에서의 중요도<br>

        형태소1, 형태소2, 형태소3, 형태소4 ...
문서1     0        0.3      0.01     0           =>  ( 0, 0.3 , 0.01, 0  ...)<br>
문서2     0.005    0.07     0        0           =>  (0.005, 0.07,0,0, ...)<br>
문서3     0        0        0.35     0           =>  (0,0,0.35,0, ...)<br>

In [24]:
for i in range(len(docs)):
    print(docs[i])

['유한양행', '얀센', '바이오', '테크', '표적', '항암', '치료제', '기술이전', '계약', '체결', '일', '공시', '기술', '수출', '금액', '달러', '한화', '원', '계약금', '달러', '개발', '허가', '매출', '단계', '마일스톤', '달러', '수령', '예정', '순', '매출액', '책정', '유한양행', '관계자', '기술이전', '계약', '수익', '인식', '임상시험', '허가', '등', '성공', '여부', '수', '미', '실현', '있다']
['유한양행', '원', '규모', '기술이전', '계약', '체결', '소식', '가격제한폭', '일', '오전', '시', '3분', '유한양행', '전날', '원', '원', '거래', '사흘', '연속', '강세', '유한양행', '글로벌', '약사', '존슨', '앤', '존슨', 'J&J', '자회사', '얀센', '바이오', '테크', '해제', '기술', '수출', '계약', '체결', '이날', '계약', '규모', '원', '달러', '반환', '의무', '계약금', '원', '달러', '이번', '계약', '얀센', '전', '세계', '개발', '제조', '상업', '독점', '권리', '국내', '개발', '상업', '권리', '유한양행', '유지', '유한양행', '얀센', '바', '이', '오텍', '내년', '단일', '요법', '병용', '요법', '글로벌', '임상시험', '공동', '진행', '예정', '유한양행', '개발', '허가', '상업', '성공', '단계', '마일스톤', '달러', '원', '수', '임상시험', '허가', '상업', '실패', '경우', '기술이전', '계약', '종료', '경우', '유한양행', '얀센', '측', '지급', '위약금']
['유한양행', '다국적', '약사', '얀센', '기술', '수출', '소식', '주가', '일', '장', '초반', '상한가', '유한양행', '이

In [17]:
# 텍스트 형식 예시 
L =['나라', '대한', '민국']
' '.join(L)

'나라 대한 민국'

In [25]:
# CountVectorizer 사용시 텍스트 형식으로 들어가야함
for i in range(len(docs)):
    docs[i] = ' '.join(docs[i])

In [26]:
docs

['유한양행 얀센 바이오 테크 표적 항암 치료제 기술이전 계약 체결 일 공시 기술 수출 금액 달러 한화 원 계약금 달러 개발 허가 매출 단계 마일스톤 달러 수령 예정 순 매출액 책정 유한양행 관계자 기술이전 계약 수익 인식 임상시험 허가 등 성공 여부 수 미 실현 있다',
 '유한양행 원 규모 기술이전 계약 체결 소식 가격제한폭 일 오전 시 3분 유한양행 전날 원 원 거래 사흘 연속 강세 유한양행 글로벌 약사 존슨 앤 존슨 J&J 자회사 얀센 바이오 테크 해제 기술 수출 계약 체결 이날 계약 규모 원 달러 반환 의무 계약금 원 달러 이번 계약 얀센 전 세계 개발 제조 상업 독점 권리 국내 개발 상업 권리 유한양행 유지 유한양행 얀센 바 이 오텍 내년 단일 요법 병용 요법 글로벌 임상시험 공동 진행 예정 유한양행 개발 허가 상업 성공 단계 마일스톤 달러 원 수 임상시험 허가 상업 실패 경우 기술이전 계약 종료 경우 유한양행 얀센 측 지급 위약금',
 '유한양행 다국적 약사 얀센 기술 수출 소식 주가 일 장 초반 상한가 유한양행 이날 오전 시 분 유가증권 시장 거래 일 원 원 거래 유한양행 얀센 바이오 테크 상피 세포 성장 인자 수용체 표적 항암 치료제 기술 이전 계약 체결 이날 장 개장 공시 이번 계약금 달러 개발 상업 단계 달러 기술 수출 규모 달러 원 삼성증권 연구원 유한양행 이번 기술 수출 계약 소식 한미약품 이후 기술 이전 계약 투자자 갈증 해소 전망 한미약품 사노피 기술 이전 계약 체결 이후 번 계약 규모 이다 말',
 '유한양행 얀센 바이오 테크 상피 세포 성장 인자 수용체 표적 항암 치료제 기술이전 계약 일 공시 기술 수출 금액 미화 달러 계약금 달러 개발 허가 매출 단계 마일스톤 달러 수령 예정 계약 지역 한국 제외 세계',
 '유한양행 원 규모 기술 수출 소식 가격제한폭 유한양행 우도 상한 일 오전 시 분 유한양행 일 대비 원 급등 원 기록 중 유한양행 우 원 원 거래 이날 유한양행 다국적 제약 사인 얀센 비소 세포 폐암 치료제 글로벌 판권 한국

In [28]:
vec = CountVectorizer()
x = vec.fit_transform(docs)

In [29]:
news_arr = x.toarray()
news_arr

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [30]:
news_arr.shape

(15, 485)

In [31]:
news_arr[0] # sparse matrix => 학습이 잘 안됨

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 3,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [32]:
vec.get_feature_names()  

C:\Users\bitcamp\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['10분',
 '20대',
 '3년',
 '3분',
 '8월',
 'k7',
 '가격제한폭',
 '가동',
 '가면',
 '가수',
 '가스',
 '가요',
 '가운데',
 '가정',
 '가창력',
 '각각',
 '각시탈',
 '각자',
 '각종',
 '갈증',
 '감미',
 '감사',
 '감성',
 '감회',
 '강세',
 '강조',
 '개발',
 '개장',
 '거래',
 '거론',
 '거짓말',
 '건빵선생과',
 '검사',
 '검출',
 '게시물',
 '게재',
 '겨울',
 '결과',
 '결정',
 '결함',
 '경구',
 '경연',
 '경우',
 '계약',
 '계약금',
 '계획',
 '고객',
 '골자',
 '곳곳',
 '공간',
 '공개',
 '공기',
 '공동',
 '공시',
 '공식',
 '공지',
 '공포',
 '관객',
 '관계자',
 '관련',
 '관심',
 '괴담',
 '교환',
 '구매',
 '구입',
 '구청',
 '국내',
 '국제',
 '군청',
 '궁금증',
 '권고',
 '권리',
 '규모',
 '극찬',
 '글로벌',
 '글쓴이',
 '금액',
 '급등',
 '기관',
 '기구',
 '기능',
 '기록',
 '기본',
 '기분',
 '기술',
 '기술이전',
 '기자',
 '기준',
 '기체',
 '기침',
 '김성주',
 '김용진',
 '김현철',
 '나무',
 '난방',
 '내년',
 '내용',
 '네이버',
 '노래',
 '논란',
 '누리꾼',
 '눈길',
 '눈물샘',
 '능력',
 '다국적',
 '다음',
 '단계',
 '단위',
 '단일',
 '달러',
 '당시',
 '대결',
 '대구',
 '대구시',
 '대비',
 '대상',
 '대여',
 '대여료',
 '대응',
 '대인',
 '데뷔',
 '도전',
 '도전자',
 '독점',
 '동안',
 '된다',
 '드라마',
 '때문',
 '라돈',
 '라운드',
 '러브송',
 '레인',
 '로만',
 '마스크',
 '마음',
 '마일스톤',
 '마지막',
 '매력

In [37]:
news_df = pd.DataFrame(news_arr, columns =vec.get_feature_names() )
news_df

C:\Users\bitcamp\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


10분  20대  3년  3분  8월  k7  가격제한폭  가동  가면  가수  ...  확대  확인  확충  환경  환경부  활동  \
0     0    0   0   0   0   0      0   0   0   0  ...   0   0   0   0    0   0   
1     0    0   0   1   0   0      1   0   0   0  ...   0   0   0   0    0   0   
2     0    0   0   0   0   0      0   0   0   0  ...   0   0   0   0    0   0   
3     0    0   0   0   0   0      0   0   0   0  ...   0   0   0   0    0   0   
4     0    0   0   0   0   0      1   0   0   0  ...   0   0   0   0    0   0   
5     1    0   0   0   1   0      0   2   0   0  ...   0   0   0   0    0   0   
6     0    1   0   0   0   0      0   0   0   0  ...   1   0   1   1    0   0   
7     0    0   0   0   0   0      0   0   0   0  ...   0   1   0   0    1   0   
8     0    0   0   0   0   0      0   0   0   0  ...   0   0   0   0    0   0   
9     0    0   0   0   0   0      0   0   0   0  ...   0   0   0   0    0   0   
10    0    0   1   0   0   0      0   0   2   3  ...   0   0   0   0    0   0   
11    0    0   0   0   0   1      0   0   1   1  ...   0   0   0   0    0   0   
12    0    0   0   0   0   0      0   0   0   4  ...   0   0   0   0    0   0   
13    0    0   0   0   0   0      0   0   0   2  ...   0   0   0   0    0   0   
14    0    0   0   0   0   0      0   0   0   0  ...   0   0   0   0    0   1   

    효소  후기  후보  흡연  
0    0   0   0   0  
1    0   0   0   0  
2    0   0   0   0  
3    0   0   0   0  
4    1   0   1   0  
5    0   0   0   0  
6    0   0   0   1  
7    0   0   0   0  
8    0   1   0   0  
9    0   0   0   0  
10   0   0   0   0  
11   0   0   0   0  
12   0   0   0   0  
13   0   0   0   0  
14   0   0   0   0  

[15 rows x 485 columns]

## clustering

In [40]:
 from sklearn.cluster import KMeans

In [42]:
kmeans = KMeans(n_clusters=3)
kmeans.fit(news_df)

KMeans(n_clusters=3)

In [52]:
# 정답값 : 00000(유한양행) 11111(라돈침대) 22222(복면가왕) 숫자는 의미없음 잘 묶였는지가 중요!

In [43]:
kmeans.labels_

array([1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 2, 1, 2, 1, 1])

In [44]:
cluster = AgglomerativeClustering(n_clusters=3, linkage='ward')
cluster.fit_predict(news_df)

array([0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 1, 0, 1, 0, 0], dtype=int64)

In [46]:
cluster = DBSCAN(eps=3, min_samples=5) # 특정거리내에 밀도 높은거 묶는지
cluster.fit_predict(news_df)

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
      dtype=int64)

### 차원축소 사용

In [49]:
from sklearn.decomposition import PCA

In [50]:
pca = PCA(n_components=2)
arr_pca = pca.fit_transform(news_df)
arr_pca

array([[ -0.081262  ,  -5.87070729],
       [ -0.15505402,  -9.95910448],
       [ -0.1238913 ,  -8.60216122],
       [ -0.12612079,  -5.55182155],
       [ -0.16603881,  -9.64045187],
       [ -3.97601048,   0.04395245],
       [ -3.31449077,  -0.6755585 ],
       [-10.66494418,   7.81956368],
       [-12.3036968 ,   9.50221538],
       [-11.61544   ,   8.95785504],
       [ 19.77047718,  11.25106749],
       [  3.32663619,  -1.08761352],
       [ 13.39289406,   6.28237953],
       [  4.10030899,  -0.58818104],
       [  1.93663272,  -1.88143411]])

In [54]:
cluster = AgglomerativeClustering(n_clusters=3, linkage='ward')
cluster.fit_predict(arr_pca)

array([0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 1, 0, 1, 0, 0], dtype=int64)

In [55]:
cluster = DBSCAN(eps=3, min_samples=5) # 특정거리내에 밀도 높은거 묶는지
cluster.fit_predict(arr_pca)

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
      dtype=int64)

In [57]:
# Tfid 사용하기: max_df, min_df,max_features 등 여러가지 paramteter 있음
vec = TfidfVectorizer()
x = vec.fit_transform(docs)
x

<15x485 sparse matrix of type '<class 'numpy.float64'>'
	with 815 stored elements in Compressed Sparse Row format>

In [58]:
news_arr = x.toarray()
news_arr

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [59]:
kmeans = KMeans(n_clusters=3)
kmeans.fit(news_arr)

KMeans(n_clusters=3)

In [64]:
# 잘된 분류
cluster = AgglomerativeClustering(n_clusters=3, linkage='ward')
cluster.fit_predict(news_arr)

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0], dtype=int64)

In [65]:
cluster = DBSCAN(eps=3, min_samples=5)
cluster.fit_predict(news_arr)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

# 다음뉴스 분류 실습해보기


### 다음뉴스 카테고리별(경제,연예,스포츠) 크롤링

In [179]:
import requests
from bs4 import BeautifulSoup

In [180]:
url_eco = 'https://news.daum.net/breakingnews/economic'

In [181]:
res = requests.get(url_eco)
res.text

'\n<!DOCTYPE html>\n\n\n\n<html lang="ko" class="os_unknown none unknown version_0 ">\n<head>\n<meta charset="utf-8">\n<meta name="referrer" content="always" />\n\n<meta property="og:author" content="Daum 뉴스" />\n<meta property="og:site_name" content="다음뉴스" />\n<meta property="og:title" content="전체뉴스"/>\n<meta property="og:image" content="https://t1.daumcdn.net/media/img-media/mobile/meta/news.png" />\n<meta property="og:description" content="다음뉴스" />\n<meta property="og:url" content="https://news.daum.net/breakingnews/economic" />\n<link rel="shortcut icon" href="https://m2.daumcdn.net/img-media/2010ci/Daum_favicon.ico">\n\n<title>전체뉴스 | 다음뉴스</title>\n\n<meta http-equiv="X-UA-Compatible" content="IE=edge">\n\n<link rel="stylesheet" type="text/css" href="//t1.daumcdn.net/media/kraken/news/bc87621/common.css.merged.css" />\n<link rel="stylesheet" type="text/css" href="//t1.daumcdn.net/media/kraken/news/bc87621/news.css.merged.css" />\n<link rel="stylesheet" type="text/css" href="//t1.da

In [182]:
soup = BeautifulSoup(res.text, 'html.parser')
soup


<!DOCTYPE html>

<html class="os_unknown none unknown version_0" lang="ko">
<head>
<meta charset="utf-8"/>
<meta content="always" name="referrer">
<meta content="Daum 뉴스" property="og:author"/>
<meta content="다음뉴스" property="og:site_name"/>
<meta content="전체뉴스" property="og:title"/>
<meta content="https://t1.daumcdn.net/media/img-media/mobile/meta/news.png" property="og:image"/>
<meta content="다음뉴스" property="og:description"/>
<meta content="https://news.daum.net/breakingnews/economic" property="og:url"/>
<link href="https://m2.daumcdn.net/img-media/2010ci/Daum_favicon.ico" rel="shortcut icon"/>
<title>전체뉴스 | 다음뉴스</title>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<link href="//t1.daumcdn.net/media/kraken/news/bc87621/common.css.merged.css" rel="stylesheet" type="text/css">
<link href="//t1.daumcdn.net/media/kraken/news/bc87621/news.css.merged.css" rel="stylesheet" type="text/css"/>
<link href="//t1.daumcdn.net/media/kraken/news/bc87621/calendar.css.merged.css" rel="styles

In [183]:
eco_lst = soup.select('#mArticle > div.box_etc > ul> li')
eco_lst
#mArticle > div.box_etc > ul

[<li>
 <a class="link_thumb" href="https://v.daum.net/v/20220406130116997">
 <img alt="대통령 집무실 이전 예비비 360억원 국무회의 의결" class="thumb_g" src="https://img1.daumcdn.net/thumb/S95x77ht.u/?fname=https%3A%2F%2Ft1.daumcdn.net%2Fnews%2F202204%2F06%2Fnewsy%2F20220406130116671dcsc.jpg&amp;scode=media">
 </img></a>
 <div class="cont_thumb">
 <strong class="tit_thumb">
 <a class="link_txt" href="https://v.daum.net/v/20220406130116997">대통령 집무실 이전 예비비 360억원 국무회의 의결</a>
 <span class="info_news">연합뉴스TV<span class="txt_bar"> · </span><span class="info_time">13:01</span></span>
 </strong>
 <div class="desc_thumb">
 <span class="link_txt">
                         대통령 집무실 용산 이전을 위한 예비비 지출안이 국무회의를 통과했습니다. 기획재정부는 오늘(6일) 임시 국무회의에서 360억원의 대통령 집무실 용산 이전용 예비비 ...
                     </span>
 </div>
 </div>
 </li>,
 <li>
 <a class="link_thumb" href="https://v.daum.net/v/20220406130016977">
 <img alt="[여행honey] 빗장 풀린 몰디브..예비 신혼 맘 설레네" class="thumb_g" src="https://img1.daumcdn.net/thumb/S95x77ht.u/?fname=https%3A%2

In [184]:
# news title
title = eco_lst[0].select('li > div > strong > a')
title

[<a class="link_txt" href="https://v.daum.net/v/20220406130116997">대통령 집무실 이전 예비비 360억원 국무회의 의결</a>]

In [311]:
# summary

summary = eco_lst[0].select('ul > li > div > div')[0].text
summary

'\n\n                        공정거래위원회가 주요 원자재의 수급 현황, 납품대금 조정 상황 등 하도급업체 납품단가 조정 실태 긴급 점검에 나섰습니다. 코로나19와 러시아·우크라이나 사태로 원...\n                    \n'

In [186]:
# 뉴스 전체기사 url

news_url = eco_lst[0].select('li > div > strong > a')[0]['href']
news_url


'https://v.daum.net/v/20220406130116997'

In [187]:
res1 = requests.get(news_url)
soup = BeautifulSoup(res1.text,'html.parser')
lines = soup.select('#harmonyContainer > section')
lines

[<section dmcf-sid="EO505kuX4g">
 <div class="video_frm" dmcf-pid="E21nkAxpCO" dmcf-ptype="kakaotv">
 <div class="layer_vod">
 <div class="vod_player">
 <iframe allowfullscreen="" class="player_iframe" dmcf-mid="ErevXgiKN4" dmcf-mtype="video/kakaotv/owner" dmcf-poster-mid="Ed8JSlHOpi" frameborder="0" height="370" id="video@ErevXgiKN4" poster="https://t1.daumcdn.net/news/202204/06/newsy/20220406130116671dcsc.jpg" scrolling="no" src="//tv.kakao.com/embed/player/cliplink/427735896?service=daum_news&amp;m_use_inline=true&amp;ios_allow_inline=true&amp;m_prevent_sdk_use=true&amp;wmode=opaque" width="100%"></iframe>
 </div>
 </div>
 </div>
 <p dmcf-pid="EU0kEraRIC" dmcf-ptype="general">대통령 집무실 용산 이전을 위한 예비비 지출안이 국무회의를 통과했습니다.</p>
 <p dmcf-pid="EkGu6NWgqH" dmcf-ptype="general">기획재정부는 오늘(6일) 임시 국무회의에서 360억원의 대통령 집무실 용산 이전용 예비비 지출안이 의결됐다고 밝혔습니다.</p>
 <p dmcf-pid="E4KmwrUM35" dmcf-ptype="general">항목별로는 위기관리센터, 경호종합상황실 등 안보 필수시설 구축비 116억원과 안보 시설 구축 뒤 시행될 국방부 이전 관련 비용 118억원, 대통령 관저로 쓰일 육군참모총장 공관 리모

In [198]:
lines[0].select('p')[0].text

'[한국경제TV 문형민 기자]'

### 크롤링 완성코드

In [321]:
url_eco = 'https://news.daum.net/breakingnews/economic?page=1'
res = requests.get(url_eco)
soup = BeautifulSoup(res.text, 'html.parser')
eco_lst = soup.select('#mArticle > div.box_etc > ul> li')
eco_lst

[<li>
 <a class="link_thumb" href="https://v.daum.net/v/20220406194614147">
 <img alt="국제선 하늘길 다시 열린다..해외여행은 언제쯤?" class="thumb_g" src="https://img1.daumcdn.net/thumb/S95x77ht.u/?fname=https%3A%2F%2Ft1.daumcdn.net%2Fnews%2F202204%2F06%2Fimbc%2F20220406194614228pvzq.jpg&amp;scode=media">
 </img></a>
 <div class="cont_thumb">
 <strong class="tit_thumb">
 <a class="link_txt" href="https://v.daum.net/v/20220406194614147">국제선 하늘길 다시 열린다..해외여행은 언제쯤?</a>
 <span class="info_news">MBC<span class="txt_bar"> · </span><span class="info_time">19:46</span></span>
 </strong>
 <div class="desc_thumb">
 <span class="link_txt">
                         [뉴스데스크] ◀ 앵커 ▶ 코로나 이후 사실상 봉쇄돼있던 국제선 항공편을, 정부가 5월부터 단계적으로 풀기로 했습니다. 최종 목표는 코로나 전 수준으로 완전 회복시...
                     </span>
 </div>
 </div>
 </li>,
 <li>
 <a class="link_thumb" href="https://v.daum.net/v/20220406194612146">
 <img alt="지난해 국내 신차 평균 가격 4000만원 첫 돌파" class="thumb_g" src="https://img1.daumcdn.net/thumb/S95x77ht.u/?fname=https%3A%2F%2Ft1.daumcd

In [360]:
# 카테고리
category = ['economic', 'entertain', 'politics']
cate_news_lst= []

for c in category:
    url_eco = 'https://news.daum.net/breakingnews/{}?page=1'.format(c)
    res = requests.get(url_eco)
    soup = BeautifulSoup(res.text, 'html.parser')
    eco_lst = soup.select('#mArticle > div.box_etc > ul> li')

    title_lst=[]
    summary_lst = []
    news_lst= []
    news_lst1 = []

    for eco in eco_lst:
        title = eco.select('li > div > strong > a')[0].text
        summary = eco.select('ul > li > div > div')[0].text
        title_lst.append(title)
        summary_lst.append(summary)

        print(title)
        print(summary)


        #전체뉴스
        news_url = eco.select('li > div > strong > a')[0]['href']
        res1 = requests.get(news_url)
        soup1 = BeautifulSoup(res1.text,'html.parser')
        lines = soup1.select('#harmonyContainer > section> p') # p태그들을 모은 값

        news=''

        for line in lines:
            new1 = line.text    # 기사 한줄
            news += new1 # 전체 기사
        print(news)
        news_lst.append(news)
        print('-'*50) 
        
    cate_news_lst.append(news_lst)

[간추린 경남] '두성산업 작업 환경 측정 누락' 업체 행정처분 외


                        [KBS 창원]고용노동부가 16명의 노동자가 급성중독 판정을 받은 창원 두성산업의 작업 환경 측정을 담당해온 업체에 대해 한 달 동안 업무 정지 처분을 내린 사실이 뒤...
                    

[KBS 창원]고용노동부가 16명의 노동자가 급성중독 판정을 받은 창원 두성산업의 작업 환경 측정을 담당해온 업체에 대해 한 달 동안 업무 정지 처분을 내린 사실이 뒤늦게 확인됐습니다.노동부는 이 업체가 두성산업 노동자가 유독물질에 최고 농도로 노출될 것으로 예상되는데도 측정 당시 노출 수준 평가를 하지 않았고, 결국 이 노동자가 급성중독 판정을 받은 사실을 확인하고 행정처분했습니다.금속노조 “대흥알앤티 대표, 구속 수사해야”금속노조 경남지부가 창원지검 앞에서 기자회견을 열어 13명의 노동자가 급성중독 판정을 받은 대흥알앤티 경영책임자의 구속 수사를 촉구했습니다.이들은 대흥알앤티가 성능이 미달된 국소배기장치를 설치하고 방독마스크 착용을 감독하지 않아 급성중독이 발생했는데도, 산업재해의 모든 책임을 세척제 제조업체에 떠넘기고 있다고 주장했습니다.“낙동강 주변 안전한 농업용수 공급 촉구”경남환경운동연합과 낙동강네트워크가 오늘(6일) 낙동강유역환경청 앞에서 낙동강권 안전한 농업용수 공급을 촉구했습니다.환경단체는 지난해 낙동강 물로 재배된 무와 쌀 등에서 녹조 독성 물질인 마이크로시스틴이 검출된 것으로 확인됐지만 정부는 아직도 녹조와 농업용수 공급 대책을 내놓지 않고 있다고 주장했습니다.공노조 “공보물·벽보 업무, 선관위가 맡아야”전국공무원노조 경남본부가 경남선관위 앞에서 기자회견을 열고 선거대행 사무는 선관위가 직접 맡아야 한다고 주장했습니다.공무원 노조는 일반 공무원들이 야간과 휴일에도 공보물 발송 작업을 해야 하고, 선거가 끝날 때까지 선거 벽보도 관리해야 한다며, 이 업무들을 선관위가 맡고 공무원의 투·개표 사무원 동원 비율도 30% 아래

산업연구원이 6일 발표한 ‘글로벌 인플레이션 요인이 국내 제조업 생산자물가에 미치는 영향과 시사점’ 보고서에 따르면 2010년부터 최근까지 흐름을 분석한 결과, 국제유가가 10% 상승하면 제조업 생산자물가는 0.68% 올랐다. 업종별로는 석탄·석유(4.33%), 화학(0.95%), 전기장비(0.76%), 1차금속(0.47%) 등 원유를 원재료로 사용하는 산업이 많은 영향을 받았다.국제 원자재 가격이 10% 상승할 때 제조업 생산자물가는 0.50% 올랐다. 석탄·석유(0.87%), 전기장비(0.81%), 화학(0.70%), 1차금속(0.44%) 업종에 미치는 영향이 컸다.글로벌 공급망 교란과 글로벌 유동성이 10%씩 확대되면 제조업 생산자물가는 각각 0.36%, 0.003% 상승하는 것으로 추정됐다.지난해 12월 기준으로 전년 동기 대비 상승률을 적용했을 때 국제유가, 국제 원자재 가격, 글로벌 공급망, 글로벌 유동성은 제조업 생산자물가를 각각 2.18%, 0.74%, 0.48%, 0.21% 높이는 것으로 분석됐다.이들 4개 요인이 생산자물가를 총 3.6% 올린 것으로, 전체 생산자물가 상승률(14.4%)에 대한 기여도가 25%나 됐다.산업연구원은 “생산자물가가 높아지면 기업의 채산성이 악화하고, 비용 전가로 인한 제품 가격 상승과 글로벌 가격경쟁력 저하로 이어져 국제수지에 부정적 영향을 준다”며 “인플레이션 확산을 경계하고 주요 요인별로 대응 방안을 마련해야 한다”고 강조했다.우상규 기자
--------------------------------------------------
코로나 이후 기초학력 미달률 급증.. 배달음식 늘며 쓰레기 대란


                        사진=연합뉴스  신종 코로나바이러스 감염증(코로나19) 발생 이후 기초학력이 미달하는 학생들이 크게 늘어난 것으로 나타났다. 영어의 경우 기초학력 미달률이 1년 새 ...
                    

6일 통계청이 발표한 ‘한국의 지속가능발전목표(SDGs) 이행보고서

최근 온라인 커뮤니티에는 손예진의 결혼식에 참석한 반려견 키티의 모습이 포착됐다. 키티는 손예진의 부케를 받은 배우 공효진의 품에 안겨 손예진의 결혼식 장면을 본 것으로 전해졌다.손예진은 자신이 키우는 반려견 키티에 대한 애정을 SNS를 통해 자주 드러냈다. 반려견과 커플룩을 입고 여행을 즐기는가 하면, 촬영장에도 반려견과 동행하기도 했다. 지난해에도 키티와 함께 찍은 사진을 게재, "엄마 따라 촬영장 왔어요. 간식만 주세요. 제발제발"이라는 귀여운 글을 올렸다. 착하고 순둥한 키티와 찍은 사진을 올릴 때마다 팬들의 관심이 폭발했다.손예진이 현빈과 결혼하며 키티에게도 현빈이라는 아빠가 생기게 됐다.한편 현빈과 손예진은 지난달 세기의 결혼식을 올렸다. 두 사람은 비공개 결혼식을 올렸으나, 이후 모든 것이 화제가 되며 결혼식이 끝난 후에도 주목 받고 있다.김미화 기자 letmein@mt.co.kr
--------------------------------------------------
제시, 신곡 'ZOOM' 비주얼 첫 공개..포토제닉 스타일


                        [한국경제TV 디지털이슈팀 유병철  기자] 제시(Jessi)가 포토제닉한 매력으로 돌아온다. 피네이션(P NATION)은 6일 낮 12시 공식 SNS를 통해 제시의 새 디지털 싱글 'ZO...
                    


--------------------------------------------------
[포토] 박소영, 웬디의 영스트리트 많이 사랑해주세요


                        개그우먼 박소영이 6일 오후 서울 목동SBS 방송국에서 열리는 '웬디의 영스트리트'사전녹음에 참석하며 포즈를 취하고 있다. 박찬우 기자 park.chanwoo@joongang.co.kr 
                    

 개그우먼 박소영이 6일 오후 서울 목동SBS 방송국에서 열리는 '웬디의 영스트리트'사전녹음에 참석하며 포즈를 취하고 있다. 박찬우 기

[스포츠경향] 유희열, 규현이 ‘싱어게인2’ Top6와 함께 레전드 유명곡 무대를 선보인다.JTBC 신규 예능프로그램 ‘유명가수전-배틀어게인’(이하 ‘유명가수전’)이 15일(금) 밤 9시 첫방송된다. ‘유명가수전’은 ‘싱어게인-무명가수전’ 시즌2(이하 ‘싱어게인2’) Top6가 레전드 유명곡 주인공들을 만나 리메이크 무대로 ‘배틀’을 펼치는 프로그램. 김기태·김소연·박현규와 윤성·이주혁·신유미가 각각 시니어팀, 주니어팀으로 나뉘어 다시 한번 음악 대결을 벌인다.또한 ‘싱어게인’ 심사위원으로 활약했던 유희열, 규현이 MC 겸 시니어, 주니어팀을 이끄는 수장으로 참여한다. ‘싱어게인2’에서 따뜻한 위로를 전하며 Top6의 성장을 도왔던 두 사람이 이번엔 심사위원과 참가자가 아닌 동료 뮤지션으로 Top6를 만나게 된 것. ‘찐 유명가수’ 유희열, 규현과 ‘갓 유명가수’ Top6가 함께 만들어 나갈 무대가 기대감을 자아내는 와중에, 2MC가 첫방송을 앞두고 반가운 인사를 전해왔다.먼저 두 사람은 ‘싱어게인2’ 팀에 대한 각별한 애정을 드러냈다. 유희열은 “심사를 통해 적지 않은 시간 지켜본 Top6와 더 많은 이야기, 음악을 나눌 수 있게 돼 기쁘다”라며 반가움을 표했다. 규현은 “’유명가수전’ 지난 시즌에도 MC를 맡았다. 이번엔 ‘배틀’이라는 포맷으로 바뀌어 기대가 크다. 거기다 든든한 희열 선배님과 함께 하기에 더욱 편한 마음으로 참여할 수 있을 것 같다”며 믿고 보는 MC 조합에 훈훈함을 얹었다.‘유명가수전’은 고품격 음악 무대는 물론 레전드 가수들과의 유쾌한 토크도 준비돼있는 예능 프로그램. 이와 관련해 유희열은 “여섯 가수의 노래 실력은 충분히 검증됐지 않나. 다만 다들 예능 경험은 많지 않아 걱정이 있었을 텐데, 정말 적극적으로 임해주고 있다”고 칭찬했다. 이어 “Top6 모두 끼가 정말 많다. 특히 김기태의 반전 예능감이 놀랍다. 방송을 보시면 시청자들도 굉장히 즐거워하실 것”이라고 귀띔했다. 규현 역시 ‘가장 예능감 넘치는 Top6’로 우승자 김기태를

국민의힘 공천관리위원회는 6·1 지방선거에 출마할 광역단체장 후보자 공모에 총 62명이 신청서를 냈다고 밝혔습니다.서울시장 선거에는 오세훈 현 시장 등 3명이, 부산시장 선거에는 박형준 현 시장이 출마합니다.대구시장 선거에는 홍준표 의원과 김재원 최고위원, 유영하 변호사, 이진숙 전 대전 MBC 사장 등 8명이 신청해 가장 높은 경쟁률을 보였습니다.경기지사 선거에는 김은혜 의원을 비롯해 강용석, 심재철, 유승민, 함진규 전 의원 등 6명이 신청서를 냈는데, 강 전 의원은 복당 절차가 끝나지 않아 ‘가접수’ 상태라고 공관위는 밝혔습니다.한편 충남지사 출마 의사를 밝혔던 김태흠 의원은 아직 신청서를 내지 않았는데, 김 의원은 KBS와의 통화에서 “출마 의사를 접은 것은 아니고, 당에서 추가 등록 연락을 줄 것으로 보고 있다”고 설명했습니다.국민의힘 공천관리위원회는 내일 서류 심사에 이어, 모레부터 후보자 면접에 나설 예정입니다.강푸른 기자 (strongblue@kbs.co.kr)
--------------------------------------------------
정부, '52시간 공약' 우려 전달..'MZ세대·건강권' 이유


                        [앵커] 또, 윤석열 당선인은 일하는 시간을 노사 합의로 바꿀 수 있게 하자고 공약을 내건 바 있습니다. 그렇게 하면, 지금의 주 52시간제가 흔들릴 수도 있단 반발이 ...
                    

또, 윤석열 당선인은 일하는 시간을 노사 합의로 바꿀 수 있게 하자고 공약을 내건 바 있습니다. 그렇게 하면, 지금의 주 52시간제가 흔들릴 수도 있단 반발이 나오는데, 정부가 이런 우려를 최근 대통령직인수위원회에 전달했습니다.성화선 기자입니다.[기자]1980년대부터 2000년대 초반에 태어난 이른바 MZ 세대에게 직장을 선택하는 기준을 물었습니다.[황인하/1998년생 : 퇴근이랑 출근 시간이 명확해야 끝나고 나서 제 개인 시간도 가질 수 있고 자기 계발하는 시간이나 자기 취미 활

In [361]:
len(title_lst)

15

In [362]:
len(summary_lst)

15

In [363]:
len(news_lst)

15

### 자연어처리를 위한 데이터프레임 만들기

In [364]:
# 각 분야 뉴스 
economic_news = cate_news_lst[0]
entertain_news = cate_news_lst[1]
politics_news = cate_news_lst[2]

In [365]:
total_news = economic_news + entertain_news + politics_news

In [366]:
# 뉴스 각 15개씩
len(total_news)

45

In [367]:
# category 넣어주기: 리스트 더해주기
cate = ['eco']*15 + ['enter']*15 + ['politics']*15
cate

['eco',
 'eco',
 'eco',
 'eco',
 'eco',
 'eco',
 'eco',
 'eco',
 'eco',
 'eco',
 'eco',
 'eco',
 'eco',
 'eco',
 'eco',
 'enter',
 'enter',
 'enter',
 'enter',
 'enter',
 'enter',
 'enter',
 'enter',
 'enter',
 'enter',
 'enter',
 'enter',
 'enter',
 'enter',
 'enter',
 'politics',
 'politics',
 'politics',
 'politics',
 'politics',
 'politics',
 'politics',
 'politics',
 'politics',
 'politics',
 'politics',
 'politics',
 'politics',
 'politics',
 'politics']

In [368]:
# 데이터프레임

news_df = pd.DataFrame({'category': cate, 'news': total_news})
news_df

category                                               news
0        eco  [KBS 창원]고용노동부가 16명의 노동자가 급성중독 판정을 받은 창원 두성산업의 ...
1        eco  [헤럴드경제]정부가 다음달부터 국제선 운항 정상화를 추진하면서 신종 코로나바이러스 ...
2        eco  카카오 공동체얼라인먼트센터(CAC)의 김성수·홍은택 공동 센터장과 남궁훈 카카오 신...
3        eco  [KBS 춘천] 지난달 강원지역의 소비자물가가 10년 만에 가장 높은 상승률을 나타...
4        eco                                                   
5        eco  [KBS 춘천]강원도가 미취업 여성의 구직 활동을 지원합니다.지원 대상은 1,100...
6        eco   미국 경제전문지 포브스가 선정한 한국 최고 부자는 김범수 카카오 창업자와 이재용 ...
7        eco  기사내용 요약 아시아 신규 생산 거점 경쟁…베트남·인도 적극 요청 국내 지자체도 삼...
8        eco  [KBS 춘천] [앵커]이어서 강릉입니다.강원 동해안에는 북방한계선 1.8km 아래...
9        eco  산업연구원이 6일 발표한 ‘글로벌 인플레이션 요인이 국내 제조업 생산자물가에 미치는...
10       eco  6일 통계청이 발표한 ‘한국의 지속가능발전목표(SDGs) 이행보고서 2022’를 보...
11       eco  <앵커>인수위원회는 재건축을 해서 이익이 많이 나면 그 가운데 일부를 거둬가는 '초...
12       eco  [뉴스데스크] ◀ 앵커 ▶지난해 우리나라의 1인당 국민소득은 3만5천달러. 인구 5...
13       eco  [KBS 광주]목포시가 통합부채 자료를 발표한 가운데 민선 7기 초반의 통합 부채금...
14       eco  [KBS 부산]지난달 부산의 소비자 물가가 1년 전보다 3.9% 올라 10년 석 달...
15     enter  [스포츠경향] ‘사랑의 꽈배기’ 윤다훈이 오소리-김진엽의 진실을 알았다.6일 오후 ...
16     enter  최근 온라인 커뮤니티에는 손예진의 결혼식에 참석한 반려견 키티의 모습이 포착됐다. ...
17     enter                                                   
18     enter   개그우먼 박소영이 6일 오후 서울 목동SBS 방송국에서 열리는 '웬디의 영스트리트...
19     enter  (서울=뉴스1) 황미현 기자 = 그룹 레드벨벳의 조이가 완벽한 V라인을 과시했다. ...
20     enter   개그우먼 박소영이 6일 오후 서울 목동SBS 방송국에서 열리는 '웬디의 영스트리트...
21     enter   (엑스포츠뉴스 김수정 인턴기자) '사랑의 꽈배기' 윤다훈이 오열했다.6일 방송된 ...
22     enter   개그우먼 박소영이 6일 오후 서울 목동SBS 방송국에서 열리는 '웬디의 영스트리트...
23     enter  [스포츠투데이 최혜진 기자] '사랑의 꽈배기' 함은정이 박재준의 친부를 밝혔다.6일...
24     enter   개그우먼 박소영이 6일 오후 서울 목동SBS 방송국에서 열리는 '웬디의 영스트리트...
25     enter  [TV리포트=김은정 기자] 남능미가 남다른 후배 사랑을 드러냈다.6일 오후 방송된 ...
26     enter  [TV리포트=이혜미 기자] 윤다훈이 함은정과 김진엽 사이에 아이가 있음을 알고 후회...
27     enter  [OSEN=박근희 기자] 한지민이 근황을 공개했다.6일 오후 배우 한지민은 본인의 ...
28     enter   개그우먼 박소영이 6일 오후 서울 목동SBS 방송국에서 열리는 '웬디의 영스트리트...
29     enter  [스포츠경향] 유희열, 규현이 ‘싱어게인2’ Top6와 함께 레전드 유명곡 무대를 ...
30  politics  [뉴스데스크] ◀ 앵커 ▶고액 고문료 논란이 불거진 한덕수 총리 후보자의 인사 검증...
31  politics  고(故) 이예람 중사 사망사건 특검법이 불발되자, 최강욱 더불어민주당 의원이 "절충...
32  politics  <앵커>민주당에서는 김영춘 전 의원에 이어, 이번에는 최재성 청와대 전 민정수석이 ...
33  politics  김여정 북한 노동당 부부장이 3일과 5일 발표한 대남 비난 담화는 남한 새 정부에 ...
34  politics  <앵커>국민의힘 김은혜 의원이 6월 지방선거의 최대 격전지로 꼽히는 경기지사 선거에...
35  politics  문재인 정부 말기에 ‘알박기 인사’ 논란이 이어지는 가운데 현 정부 주요 관련자들이...
36  politics  국민의힘 공천관리위원회는 6·1 지방선거에 출마할 광역단체장 후보자 공모에 총 62...
37  politics  또, 윤석열 당선인은 일하는 시간을 노사 합의로 바꿀 수 있게 하자고 공약을 내건 ...
38  politics  대통령 비서실 조직을 대대적으로 개편하겠다는 윤석열 대통령 당선인의 구상이 점점 구...
39  politics  (부산=연합뉴스) 오수희 기자 = 6·1 지방선거에 출마할 국민의힘 부산시장 후보자...
40  politics  청와대는 문재인 대통령의 부인 김정숙 여사의 의류 구입비용을 대통령비서실 특별활동비...
41  politics  [KBS 청주] [앵커]6월 지방선거를 앞두고 관전 포인트를 살펴보는 뉴스7 충북의...
42  politics  오세훈 현 서울시장이 송영길 더불어민주당 전 대표와의 가상 양자대결에서 오차범위 밖...
43  politics  윤석열 당선인의 용산 집무실 이전에 필요한 예비비 360억 원을 정부가 오늘(6일)...
44  politics  <앵커>대통령직인수위원회가 서울시, 국토부의 주택 정책 담당자들과 만났습니다. 당선...

In [370]:
# news_df.to_csv('./data/daum_news.csv')

In [ ]:
## 