# 뉴스 분류하기

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from konlpy.tag import Hannanum, Komoran, Kkma, Twitter
from sklearn.cluster import AgglomerativeClustering, kmeans_plusplus, DBSCAN
import scipy.cluster.hierarchy as shc
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer

In [3]:
han = Hannanum()

In [7]:
data = pd.read_excel('../data/clustering_data.xlsx')
data

검색어  \
0                                    유한양행   
1                                    유한양행   
2                                    유한양행   
3                                    유한양행   
4                                    유한양행   
5                                      라돈   
6                                      라돈   
7                                      라돈   
8                                      라돈   
9                                      라돈   
10                               복면가왕 왕밤빵   
11                               복면가왕 왕밤빵   
12                               복면가왕 왕밤빵   
13                               복면가왕 왕밤빵   
14  복면가왕 왕밤빵15:15B1213:1614:1613:16B11:16   

                                                 기사내용  
0   유한양행은 얀센 바이오테크(Janssen Biotech Inc)와 EGFR표적 항암...  
1   유한양행이 1조4000억원 규모의 기술이전 계약 체결 소식에 가격제한폭까지 치솟았다...  
2   유한양행이 다국적 제약사 얀센에 기술수출했다는 소식에 주가가 5일 장 초반 상한가를...  
3   유한양행은 얀센 바이오테크((Janssen Biotech, Inc.)와 EGFR(상...  
4   유한양행이 1조4000억원 규모 기술 수출 소식에 가격제한폭까지 치솟았다. 유한양행...  
5   최근 침대 매트리스에 이어 온수매트에서도 라돈이 검출됐다는 소식이 알려지면서, 가정...  
6    침대, 생리대, 마스크 등에서 라돈이 검출되면서, 발암 물질 ‘라돈’에 대한 관심...  
7   하이젠 온수매트가 '라돈 온수매트'로 언급되고 있다.\n최근 한 온라인커뮤니티에서는...  
8   겨울 난방 제품인 온수매트에서 라돈이 검출된 가운데 해당 업체가 별 문제가 되지 않...  
9   매트리스, 생리대에 이어 온수 매트에서도 라돈이 검출돼 이슈로 떠올랐다.\n5일 오...  
10  복면가왕’ 88대 가왕 자리는 2연승의 왕밤빵이 차지했다.\n4일 오후 방송된 MB...  
11  복면가왕'에 출연해 왕밤빵에 패하면서 얼굴을 공개한 '축음기' 천단비에 관심이 쏠리...  
12  지난 4일 방송된 MBC ‘복면가왕’에서는 왕밤빵에 맞서 축음기, 조커, 북극곰 버...  
13  복면가왕' 왕밤빵의 정체가 더욱더 오리무중에 빠졌다. \n4일 방송된 MBC 예능프...  
14  복면가왕' 왕밤빵이 첫 방어전에 성공하며 2연승을 차지했다.\n지난 4일 방송된 M...

In [8]:
# 12행 뉴스
data.iloc[11,1]

'복면가왕\'에 출연해 왕밤빵에 패하면서 얼굴을 공개한 \'축음기\' 천단비에 관심이 쏠리고 있다.\n지난 4일 방송된 MBC 예능프로그램 \'복면가왕\'에서는 왕밤빵과 축음기가 88대 가왕 자리를 놓고 대결을 벌였다. 그 결과 왕밤빵이 가왕에 올랐다.\n이날 축음기는 박정현의 \'미아\'로 남다른 가창력을 자랑했지만 왕밤빵에 패하고 말았다. 이에 축음기는 가면을 벗었고, 드러난 정체는 바로 가수 천단비였다.\n천단비는 방송이 끝난 후 자신의 인스타그램을 통해 "제게 노래하는 무대가 소중하지 않은 순간이 있겠냐마는 유독 또 소중하고 행복한 순간이 하나 더 생겼다. 열심히 더 노래하겠다"고 \'복면가왕\' 출연 소감을 전했다.\n천단비는 2015년 Mnet \'슈퍼스타K7\'에 출연하며 주목받았지만 데뷔는 훨씬 빨랐다. 2005년 SBS \'건빵선생과 별사탕\' OST \'눈물샘\'으로 데뷔한 바 있다.\n\'슈스케7\' 준우승 후 각종 OST에 참여하며 노래를 불러온 천단비는 지난해  \'어느 봄의 거짓말\'을 발매해 많은 팬들의 사랑을 받기도 했다.'

## 전처리

In [9]:
 # 유사한 텍스트끼리 묶는다

In [22]:
# 명사만 모아주기
kor = Komoran()

docs = []
for news in data['기사내용']:
    docs.append(kor.nouns(news))

In [23]:
# 명사만 모은 리스트
docs

[['유한양행',
  '얀센',
  '바이오',
  '테크',
  '표적',
  '항암',
  '치료제',
  '기술이전',
  '계약',
  '체결',
  '일',
  '공시',
  '기술',
  '수출',
  '금액',
  '달러',
  '한화',
  '원',
  '계약금',
  '달러',
  '개발',
  '허가',
  '매출',
  '단계',
  '마일스톤',
  '달러',
  '수령',
  '예정',
  '순',
  '매출액',
  '책정',
  '유한양행',
  '관계자',
  '기술이전',
  '계약',
  '수익',
  '인식',
  '임상시험',
  '허가',
  '등',
  '성공',
  '여부',
  '수',
  '미',
  '실현',
  '있다'],
 ['유한양행',
  '원',
  '규모',
  '기술이전',
  '계약',
  '체결',
  '소식',
  '가격제한폭',
  '일',
  '오전',
  '시',
  '3분',
  '유한양행',
  '전날',
  '원',
  '원',
  '거래',
  '사흘',
  '연속',
  '강세',
  '유한양행',
  '글로벌',
  '약사',
  '존슨',
  '앤',
  '존슨',
  'J&J',
  '자회사',
  '얀센',
  '바이오',
  '테크',
  '해제',
  '기술',
  '수출',
  '계약',
  '체결',
  '이날',
  '계약',
  '규모',
  '원',
  '달러',
  '반환',
  '의무',
  '계약금',
  '원',
  '달러',
  '이번',
  '계약',
  '얀센',
  '전',
  '세계',
  '개발',
  '제조',
  '상업',
  '독점',
  '권리',
  '국내',
  '개발',
  '상업',
  '권리',
  '유한양행',
  '유지',
  '유한양행',
  '얀센',
  '바',
  '이',
  '오텍',
  '내년',
  '단일',
  '요법',
  '병용',
  '요법',
  '글로벌',
  '임상시험',
  '공동',
  '진행',


## 단어를 숫자로 전환

### 1. counter vectorizing

        형태소1, 형태소2, 형태소3, 형태소4 ...
문서1     0        2        1        0   =>  (0,2,1,0  ...)<br>
문서2     1        1        0        0           =>  (1,1,0,0, ...)<br>
문서3     0        0        3        0           =>  (0,0,3,0, ...)<br>
...

### 2. tfidf vectorizing

문서에서 형태소1 등장수 : tf<br>
전체 문서에서 형태소1이 등장한 문서수 : idf<br>
tfidf = tf/idf => 특정 형태소가 특정 문서에서의 중요도<br>

        형태소1, 형태소2, 형태소3, 형태소4 ...
문서1     0        0.3      0.01     0           =>  ( 0, 0.3 , 0.01, 0  ...)<br>
문서2     0.005    0.07     0        0           =>  (0.005, 0.07,0,0, ...)<br>
문서3     0        0        0.35     0           =>  (0,0,0.35,0, ...)<br>

In [24]:
for i in range(len(docs)):
    print(docs[i])

['유한양행', '얀센', '바이오', '테크', '표적', '항암', '치료제', '기술이전', '계약', '체결', '일', '공시', '기술', '수출', '금액', '달러', '한화', '원', '계약금', '달러', '개발', '허가', '매출', '단계', '마일스톤', '달러', '수령', '예정', '순', '매출액', '책정', '유한양행', '관계자', '기술이전', '계약', '수익', '인식', '임상시험', '허가', '등', '성공', '여부', '수', '미', '실현', '있다']
['유한양행', '원', '규모', '기술이전', '계약', '체결', '소식', '가격제한폭', '일', '오전', '시', '3분', '유한양행', '전날', '원', '원', '거래', '사흘', '연속', '강세', '유한양행', '글로벌', '약사', '존슨', '앤', '존슨', 'J&J', '자회사', '얀센', '바이오', '테크', '해제', '기술', '수출', '계약', '체결', '이날', '계약', '규모', '원', '달러', '반환', '의무', '계약금', '원', '달러', '이번', '계약', '얀센', '전', '세계', '개발', '제조', '상업', '독점', '권리', '국내', '개발', '상업', '권리', '유한양행', '유지', '유한양행', '얀센', '바', '이', '오텍', '내년', '단일', '요법', '병용', '요법', '글로벌', '임상시험', '공동', '진행', '예정', '유한양행', '개발', '허가', '상업', '성공', '단계', '마일스톤', '달러', '원', '수', '임상시험', '허가', '상업', '실패', '경우', '기술이전', '계약', '종료', '경우', '유한양행', '얀센', '측', '지급', '위약금']
['유한양행', '다국적', '약사', '얀센', '기술', '수출', '소식', '주가', '일', '장', '초반', '상한가', '유한양행', '이

In [17]:
# 텍스트 형식 예시 
L =['나라', '대한', '민국']
' '.join(L)

'나라 대한 민국'

In [25]:
# CountVectorizer 사용시 텍스트 형식으로 들어가야함

for i in range(len(docs)):
    docs[i] = ' '.join(docs[i])

In [26]:
docs

['유한양행 얀센 바이오 테크 표적 항암 치료제 기술이전 계약 체결 일 공시 기술 수출 금액 달러 한화 원 계약금 달러 개발 허가 매출 단계 마일스톤 달러 수령 예정 순 매출액 책정 유한양행 관계자 기술이전 계약 수익 인식 임상시험 허가 등 성공 여부 수 미 실현 있다',
 '유한양행 원 규모 기술이전 계약 체결 소식 가격제한폭 일 오전 시 3분 유한양행 전날 원 원 거래 사흘 연속 강세 유한양행 글로벌 약사 존슨 앤 존슨 J&J 자회사 얀센 바이오 테크 해제 기술 수출 계약 체결 이날 계약 규모 원 달러 반환 의무 계약금 원 달러 이번 계약 얀센 전 세계 개발 제조 상업 독점 권리 국내 개발 상업 권리 유한양행 유지 유한양행 얀센 바 이 오텍 내년 단일 요법 병용 요법 글로벌 임상시험 공동 진행 예정 유한양행 개발 허가 상업 성공 단계 마일스톤 달러 원 수 임상시험 허가 상업 실패 경우 기술이전 계약 종료 경우 유한양행 얀센 측 지급 위약금',
 '유한양행 다국적 약사 얀센 기술 수출 소식 주가 일 장 초반 상한가 유한양행 이날 오전 시 분 유가증권 시장 거래 일 원 원 거래 유한양행 얀센 바이오 테크 상피 세포 성장 인자 수용체 표적 항암 치료제 기술 이전 계약 체결 이날 장 개장 공시 이번 계약금 달러 개발 상업 단계 달러 기술 수출 규모 달러 원 삼성증권 연구원 유한양행 이번 기술 수출 계약 소식 한미약품 이후 기술 이전 계약 투자자 갈증 해소 전망 한미약품 사노피 기술 이전 계약 체결 이후 번 계약 규모 이다 말',
 '유한양행 얀센 바이오 테크 상피 세포 성장 인자 수용체 표적 항암 치료제 기술이전 계약 일 공시 기술 수출 금액 미화 달러 계약금 달러 개발 허가 매출 단계 마일스톤 달러 수령 예정 계약 지역 한국 제외 세계',
 '유한양행 원 규모 기술 수출 소식 가격제한폭 유한양행 우도 상한 일 오전 시 분 유한양행 일 대비 원 급등 원 기록 중 유한양행 우 원 원 거래 이날 유한양행 다국적 제약 사인 얀센 비소 세포 폐암 치료제 글로벌 판권 한국

In [28]:
# 명사를 모은 데이터를 벡터화 시키기
vec = CountVectorizer()
x = vec.fit_transform(docs)

In [29]:
news_arr = x.toarray()
news_arr

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [30]:
news_arr.shape

(15, 485)

In [31]:
news_arr[0] # sparse matrix => 학습이 잘 안됨

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 3,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [32]:
vec.get_feature_names()  

C:\Users\bitcamp\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['10분',
 '20대',
 '3년',
 '3분',
 '8월',
 'k7',
 '가격제한폭',
 '가동',
 '가면',
 '가수',
 '가스',
 '가요',
 '가운데',
 '가정',
 '가창력',
 '각각',
 '각시탈',
 '각자',
 '각종',
 '갈증',
 '감미',
 '감사',
 '감성',
 '감회',
 '강세',
 '강조',
 '개발',
 '개장',
 '거래',
 '거론',
 '거짓말',
 '건빵선생과',
 '검사',
 '검출',
 '게시물',
 '게재',
 '겨울',
 '결과',
 '결정',
 '결함',
 '경구',
 '경연',
 '경우',
 '계약',
 '계약금',
 '계획',
 '고객',
 '골자',
 '곳곳',
 '공간',
 '공개',
 '공기',
 '공동',
 '공시',
 '공식',
 '공지',
 '공포',
 '관객',
 '관계자',
 '관련',
 '관심',
 '괴담',
 '교환',
 '구매',
 '구입',
 '구청',
 '국내',
 '국제',
 '군청',
 '궁금증',
 '권고',
 '권리',
 '규모',
 '극찬',
 '글로벌',
 '글쓴이',
 '금액',
 '급등',
 '기관',
 '기구',
 '기능',
 '기록',
 '기본',
 '기분',
 '기술',
 '기술이전',
 '기자',
 '기준',
 '기체',
 '기침',
 '김성주',
 '김용진',
 '김현철',
 '나무',
 '난방',
 '내년',
 '내용',
 '네이버',
 '노래',
 '논란',
 '누리꾼',
 '눈길',
 '눈물샘',
 '능력',
 '다국적',
 '다음',
 '단계',
 '단위',
 '단일',
 '달러',
 '당시',
 '대결',
 '대구',
 '대구시',
 '대비',
 '대상',
 '대여',
 '대여료',
 '대응',
 '대인',
 '데뷔',
 '도전',
 '도전자',
 '독점',
 '동안',
 '된다',
 '드라마',
 '때문',
 '라돈',
 '라운드',
 '러브송',
 '레인',
 '로만',
 '마스크',
 '마음',
 '마일스톤',
 '마지막',
 '매력

In [37]:
news_df = pd.DataFrame(news_arr, columns =vec.get_feature_names() )
news_df

C:\Users\bitcamp\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


10분  20대  3년  3분  8월  k7  가격제한폭  가동  가면  가수  ...  확대  확인  확충  환경  환경부  활동  \
0     0    0   0   0   0   0      0   0   0   0  ...   0   0   0   0    0   0   
1     0    0   0   1   0   0      1   0   0   0  ...   0   0   0   0    0   0   
2     0    0   0   0   0   0      0   0   0   0  ...   0   0   0   0    0   0   
3     0    0   0   0   0   0      0   0   0   0  ...   0   0   0   0    0   0   
4     0    0   0   0   0   0      1   0   0   0  ...   0   0   0   0    0   0   
5     1    0   0   0   1   0      0   2   0   0  ...   0   0   0   0    0   0   
6     0    1   0   0   0   0      0   0   0   0  ...   1   0   1   1    0   0   
7     0    0   0   0   0   0      0   0   0   0  ...   0   1   0   0    1   0   
8     0    0   0   0   0   0      0   0   0   0  ...   0   0   0   0    0   0   
9     0    0   0   0   0   0      0   0   0   0  ...   0   0   0   0    0   0   
10    0    0   1   0   0   0      0   0   2   3  ...   0   0   0   0    0   0   
11    0    0   0   0   0   1      0   0   1   1  ...   0   0   0   0    0   0   
12    0    0   0   0   0   0      0   0   0   4  ...   0   0   0   0    0   0   
13    0    0   0   0   0   0      0   0   0   2  ...   0   0   0   0    0   0   
14    0    0   0   0   0   0      0   0   0   0  ...   0   0   0   0    0   1   

    효소  후기  후보  흡연  
0    0   0   0   0  
1    0   0   0   0  
2    0   0   0   0  
3    0   0   0   0  
4    1   0   1   0  
5    0   0   0   0  
6    0   0   0   1  
7    0   0   0   0  
8    0   1   0   0  
9    0   0   0   0  
10   0   0   0   0  
11   0   0   0   0  
12   0   0   0   0  
13   0   0   0   0  
14   0   0   0   0  

[15 rows x 485 columns]

## clustering

In [4]:
 from sklearn.cluster import KMeans

In [ ]:
news_df = pd.read_csv('../dat')

In [5]:
kmeans = KMeans(n_clusters=3)
kmeans.fit(news_df)

NameError: name 'news_df' is not defined

In [ ]:
# 정답값 : 00000(유한양행) 11111(라돈침대) 22222(복면가왕) 숫자는 의미없음 잘 묶였는지가 중요!

In [43]:
kmeans.labels_

array([1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 2, 1, 2, 1, 1])

In [44]:
cluster = AgglomerativeClustering(n_clusters=3, linkage='ward')
cluster.fit_predict(news_df)

array([0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 1, 0, 1, 0, 0], dtype=int64)

In [46]:
cluster = DBSCAN(eps=3, min_samples=5) # 특정거리내에 밀도 높은거 묶는지
cluster.fit_predict(news_df)

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
      dtype=int64)

### 차원축소 사용

In [49]:
from sklearn.decomposition import PCA

In [50]:
pca = PCA(n_components=2)
arr_pca = pca.fit_transform(news_df)
arr_pca

array([[ -0.081262  ,  -5.87070729],
       [ -0.15505402,  -9.95910448],
       [ -0.1238913 ,  -8.60216122],
       [ -0.12612079,  -5.55182155],
       [ -0.16603881,  -9.64045187],
       [ -3.97601048,   0.04395245],
       [ -3.31449077,  -0.6755585 ],
       [-10.66494418,   7.81956368],
       [-12.3036968 ,   9.50221538],
       [-11.61544   ,   8.95785504],
       [ 19.77047718,  11.25106749],
       [  3.32663619,  -1.08761352],
       [ 13.39289406,   6.28237953],
       [  4.10030899,  -0.58818104],
       [  1.93663272,  -1.88143411]])

In [54]:
cluster = AgglomerativeClustering(n_clusters=3, linkage='ward')
cluster.fit_predict(arr_pca)

array([0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 1, 0, 1, 0, 0], dtype=int64)

In [55]:
cluster = DBSCAN(eps=3, min_samples=5) # 특정거리내에 밀도 높은거 묶는지
cluster.fit_predict(arr_pca)

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
      dtype=int64)

In [57]:
# Tfid 사용하기: max_df, min_df,max_features 등 여러가지 paramteter 있음
vec = TfidfVectorizer()
x = vec.fit_transform(docs)
x

<15x485 sparse matrix of type '<class 'numpy.float64'>'
	with 815 stored elements in Compressed Sparse Row format>

In [58]:
news_arr = x.toarray()
news_arr

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [59]:
kmeans = KMeans(n_clusters=3)
kmeans.fit(news_arr)

KMeans(n_clusters=3)

In [64]:
# 잘된 분류
cluster = AgglomerativeClustering(n_clusters=3, linkage='ward')
cluster.fit_predict(news_arr)

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0], dtype=int64)

In [65]:
cluster = DBSCAN(eps=3, min_samples=5)
cluster.fit_predict(news_arr)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

# 다음뉴스 분류 실습해보기


### 다음뉴스 카테고리별(경제,연예,스포츠) 크롤링

In [6]:
import requests
from bs4 import BeautifulSoup

In [7]:
url_eco = 'https://news.daum.net/breakingnews/economic'

In [8]:
res = requests.get(url_eco)
res.text

'\n<!DOCTYPE html>\n\n\n\n<html lang="ko" class="os_unknown none unknown version_0 ">\n<head>\n<meta charset="utf-8">\n<meta name="referrer" content="always" />\n\n<meta property="og:author" content="Daum 뉴스" />\n<meta property="og:site_name" content="다음뉴스" />\n<meta property="og:title" content="전체뉴스"/>\n<meta property="og:image" content="https://t1.daumcdn.net/media/img-media/mobile/meta/news.png" />\n<meta property="og:description" content="다음뉴스" />\n<meta property="og:url" content="https://news.daum.net/breakingnews/economic" />\n<link rel="shortcut icon" href="https://m2.daumcdn.net/img-media/2010ci/Daum_favicon.ico">\n\n<title>전체뉴스 | 다음뉴스</title>\n\n<meta http-equiv="X-UA-Compatible" content="IE=edge">\n\n<link rel="stylesheet" type="text/css" href="//t1.daumcdn.net/media/kraken/news/bc87621/common.css.merged.css" />\n<link rel="stylesheet" type="text/css" href="//t1.daumcdn.net/media/kraken/news/bc87621/news.css.merged.css" />\n<link rel="stylesheet" type="text/css" href="//t1.da

In [9]:
soup = BeautifulSoup(res.text, 'html.parser')
soup


<!DOCTYPE html>

<html class="os_unknown none unknown version_0" lang="ko">
<head>
<meta charset="utf-8"/>
<meta content="always" name="referrer">
<meta content="Daum 뉴스" property="og:author"/>
<meta content="다음뉴스" property="og:site_name"/>
<meta content="전체뉴스" property="og:title"/>
<meta content="https://t1.daumcdn.net/media/img-media/mobile/meta/news.png" property="og:image"/>
<meta content="다음뉴스" property="og:description"/>
<meta content="https://news.daum.net/breakingnews/economic" property="og:url"/>
<link href="https://m2.daumcdn.net/img-media/2010ci/Daum_favicon.ico" rel="shortcut icon"/>
<title>전체뉴스 | 다음뉴스</title>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<link href="//t1.daumcdn.net/media/kraken/news/bc87621/common.css.merged.css" rel="stylesheet" type="text/css">
<link href="//t1.daumcdn.net/media/kraken/news/bc87621/news.css.merged.css" rel="stylesheet" type="text/css"/>
<link href="//t1.daumcdn.net/media/kraken/news/bc87621/calendar.css.merged.css" rel="styles

In [10]:
eco_lst = soup.select('#mArticle > div.box_etc > ul> li')
eco_lst
#mArticle > div.box_etc > ul

[<li>
 <a class="link_thumb" href="https://v.daum.net/v/20220406233124773">
 <img alt="'시멘트 부족' 해소 위한 긴급회의..&quot;35% 추가 생산&quot;" class="thumb_g" src="https://img1.daumcdn.net/thumb/S95x77ht.u/?fname=https%3A%2F%2Ft1.daumcdn.net%2Fnews%2F202204%2F06%2FYTN%2F20220406233124935sndg.jpg&amp;scode=media">
 </img></a>
 <div class="cont_thumb">
 <strong class="tit_thumb">
 <a class="link_txt" href="https://v.daum.net/v/20220406233124773">'시멘트 부족' 해소 위한 긴급회의.."35% 추가 생산"</a>
 <span class="info_news">YTN<span class="txt_bar"> · </span><span class="info_time">23:31</span></span>
 </strong>
 <div class="desc_thumb">
 <span class="link_txt">
                         최근 시멘트 공급 부족과 가격 급등이 이어지자 정부는 시멘트 업계 등과 함께 회의를 열어 2분기부터 총력 생산 체제에 돌입하기로 했습니다. 이에따라 국내 7개 시멘...
                     </span>
 </div>
 </div>
 </li>,
 <li>
 <a class="link_thumb" href="https://v.daum.net/v/20220406232546735">
 <img alt="미 국채금리 3년여래 최고..뉴욕 증시 일제히 급락" class="thumb_g" src="https://img1.daumcdn.net/thumb/S95x77ht.u/?fname=h

In [11]:
# news title
title = eco_lst[0].select('li > div > strong > a')
title

[<a class="link_txt" href="https://v.daum.net/v/20220406233124773">'시멘트 부족' 해소 위한 긴급회의.."35% 추가 생산"</a>]

In [12]:
# summary

summary = eco_lst[0].select('ul > li > div > div')[0].text
summary

'\n\n                        최근 시멘트 공급 부족과 가격 급등이 이어지자 정부는 시멘트 업계 등과 함께 회의를 열어 2분기부터 총력 생산 체제에 돌입하기로 했습니다. 이에따라 국내 7개 시멘...\n                    \n'

In [13]:
# 뉴스 전체기사 url

news_url = eco_lst[0].select('li > div > strong > a')[0]['href']
news_url


'https://v.daum.net/v/20220406233124773'

In [14]:
res1 = requests.get(news_url)
soup = BeautifulSoup(res1.text,'html.parser')
lines = soup.select('#harmonyContainer > section')
lines

[<section dmcf-sid="E5C4imSYI7">
 <div class="video_frm" dmcf-pid="EXcHqHI3MR" dmcf-ptype="kakaotv">
 <div class="layer_vod">
 <div class="vod_player">
 <iframe allowfullscreen="" class="player_iframe" dmcf-mid="Eq9ZIjt1EN" dmcf-mtype="video/kakaotv/owner" dmcf-poster-mid="ERUsnSgFZv" frameborder="0" height="370" id="video@Eq9ZIjt1EN" poster="https://t1.daumcdn.net/news/202204/06/YTN/20220406233124935sndg.jpg" scrolling="no" src="//tv.kakao.com/embed/player/cliplink/427752676?service=daum_news&amp;m_use_inline=true&amp;ios_allow_inline=true&amp;m_prevent_sdk_use=true&amp;wmode=opaque" width="100%"></iframe>
 </div>
 </div>
 </div>
 <p dmcf-pid="EDOFrCedSk" dmcf-ptype="general">최근 시멘트 공급 부족과 가격 급등이 이어지자 정부는 시멘트 업계 등과 함께 회의를 열어 2분기부터 총력 생산 체제에 돌입하기로 했습니다. </p>
 <p dmcf-pid="ElmaiMCJgN" dmcf-ptype="general">이에따라 국내 7개 시멘트 회사는 전 분기보다 35% 이상 시멘트를 추가 생산하고, 수출 물량은 내수로 전환해 공급 불안을 해소할 계획입니다. </p>
 <p dmcf-pid="EnLHczuTXB" dmcf-ptype="general">시멘트의 원료인 유연탄 가격 급등과 관련해선 러시아에 대한 수입 의존도를 줄여 일단 공급망을 

In [15]:
lines[0].select('p')[0].text

'최근 시멘트 공급 부족과 가격 급등이 이어지자 정부는 시멘트 업계 등과 함께 회의를 열어 2분기부터 총력 생산 체제에 돌입하기로 했습니다. '

### 크롤링 완성코드

In [16]:
url_eco = 'https://news.daum.net/breakingnews/economic?page=1'
res = requests.get(url_eco)
soup = BeautifulSoup(res.text, 'html.parser')
eco_lst = soup.select('#mArticle > div.box_etc > ul> li')
eco_lst

[<li>
 <a class="link_thumb" href="https://v.daum.net/v/20220406233124773">
 <img alt="'시멘트 부족' 해소 위한 긴급회의..&quot;35% 추가 생산&quot;" class="thumb_g" src="https://img1.daumcdn.net/thumb/S95x77ht.u/?fname=https%3A%2F%2Ft1.daumcdn.net%2Fnews%2F202204%2F06%2FYTN%2F20220406233124935sndg.jpg&amp;scode=media">
 </img></a>
 <div class="cont_thumb">
 <strong class="tit_thumb">
 <a class="link_txt" href="https://v.daum.net/v/20220406233124773">'시멘트 부족' 해소 위한 긴급회의.."35% 추가 생산"</a>
 <span class="info_news">YTN<span class="txt_bar"> · </span><span class="info_time">23:31</span></span>
 </strong>
 <div class="desc_thumb">
 <span class="link_txt">
                         최근 시멘트 공급 부족과 가격 급등이 이어지자 정부는 시멘트 업계 등과 함께 회의를 열어 2분기부터 총력 생산 체제에 돌입하기로 했습니다. 이에따라 국내 7개 시멘...
                     </span>
 </div>
 </div>
 </li>,
 <li>
 <a class="link_thumb" href="https://v.daum.net/v/20220406232546735">
 <img alt="미 국채금리 3년여래 최고..뉴욕 증시 일제히 급락" class="thumb_g" src="https://img1.daumcdn.net/thumb/S95x77ht.u/?fname=h

In [17]:
# 카테고리
category = ['economic', 'entertain', 'politics']
cate_news_lst= []

for c in category:
    url_eco = 'https://news.daum.net/breakingnews/{}?page=1'.format(c)
    res = requests.get(url_eco)
    soup = BeautifulSoup(res.text, 'html.parser')
    eco_lst = soup.select('#mArticle > div.box_etc > ul> li')

    title_lst=[]
    summary_lst = []
    news_lst= []
    news_lst1 = []

    for eco in eco_lst:
        title = eco.select('li > div > strong > a')[0].text
        summary = eco.select('ul > li > div > div')[0].text
        title_lst.append(title)
        summary_lst.append(summary)

        print(title)
        print(summary)


        #전체뉴스
        news_url = eco.select('li > div > strong > a')[0]['href']
        res1 = requests.get(news_url)
        soup1 = BeautifulSoup(res1.text,'html.parser')
        lines = soup1.select('#harmonyContainer > section> p') # p태그들을 모은 값

        news=''

        for line in lines:
            new1 = line.text    # 기사 한줄
            news += new1 # 전체 기사
        print(news)
        news_lst.append(news)
        print('-'*50) 
        
    cate_news_lst.append(news_lst)

'시멘트 부족' 해소 위한 긴급회의.."35% 추가 생산"


                        최근 시멘트 공급 부족과 가격 급등이 이어지자 정부는 시멘트 업계 등과 함께 회의를 열어 2분기부터 총력 생산 체제에 돌입하기로 했습니다. 이에따라 국내 7개 시멘...
                    

최근 시멘트 공급 부족과 가격 급등이 이어지자 정부는 시멘트 업계 등과 함께 회의를 열어 2분기부터 총력 생산 체제에 돌입하기로 했습니다. 이에따라 국내 7개 시멘트 회사는 전 분기보다 35% 이상 시멘트를 추가 생산하고, 수출 물량은 내수로 전환해 공급 불안을 해소할 계획입니다. 시멘트의 원료인 유연탄 가격 급등과 관련해선 러시아에 대한 수입 의존도를 줄여 일단 공급망을 안정화하기로 했습니다. 지금까지 유연탄은 러시아에서 75%, 호주에서 25%를 수입해왔으나 앞으로는 러시아 54%, 호주 46%로 비중을 조정하기로 했습니다. 하지만 유연탄 가격이 이미 지난해보다 2배가량 오른 상태라 레미콘 업계와 건설업계 간 이견 조정이 쉽지 않아 추가 논의가 불가피할 것으로 보입니다. YTN 박홍구 (hkpark@ytn.co.kr)※ '당신의 제보가 뉴스가 됩니다' [카카오톡] YTN 검색해 채널 추가 [전화] 02-398-8585 [메일] social@ytn.co.kr
--------------------------------------------------
미 국채금리 3년여래 최고..뉴욕 증시 일제히 급락


                        [뉴욕=이데일리 김정남 특파원] 미국 뉴욕 증시의 3대 지수가 6일(현지시간) 장 초반 일제히 급락하고 있다. 연방준비제도(Fed)의 가파른 긴축 전망이 커지면서, 침체 ...
                    

 [뉴욕=이데일리 김정남 특파원] 미국 뉴욕 증시의 3대 지수가 6일(현지시간) 장 초반 일제히 급락하고 있다. 연방준비제도(Fed)의 가파른 긴축 전망이 커지면서, 침체 우려가 고개를 들고 있기

LG전자가 6일부터 오는 6월 5일까지 부산 광안리에 위치한 ‘더 브릿지 호텔’에서 올레드 TV로 게임을 즐길 수 있는 ‘금성 오락실’을 운영한다고 밝혔다. 지하 1층부터 지상 3층 공간에서 추억의 오락실 게임부터 최신 콘솔 게임까지 10여대의 올레드TV로 자유롭게 이용할 수 있다. 지난해 서울 성수동에서 처음 선보였고, 당시 하루 평균 400명 이상이 방문하는 등 2030세대로부터 큰 호응을 얻었다.LG전자 제공
--------------------------------------------------
우크라 "노획한 러 진공폭탄 발사기로 러군 공격"


                        [이데일리 이은정 기자] 우크라이나군이 노획한 ‘진공폭탄’ 발사기로 러시아군을 공격했다. 러시아 미사일 공격으로 파괴된 우크라 키예프 인근 도시 건물.(사진=바실...
                    

 [이데일리 이은정 기자] 우크라이나군이 노획한 ‘진공폭탄’ 발사기로 러시아군을 공격했다. 이 장치는 열압력탄을 발사할 수 있다. 진공폭탄으로 불리는 열압력탄은 재래식 폭약 대신 가연성 액체나 분말가루를 탄두에 넣어 목표물에 배출되면 분무운을 퍼뜨린 뒤 이를 점화시키는 방식의 대량살상무기다.진공폭탄은 핵폭탄을 제외한 폭탄 중 가장 큰 위력을 갖고 있으며, 러시아는 옛 소련 시절인 1979년 아프가니스탄 침공, 1994년 1차 체첸전쟁 등에서도 진공폭탄을 투하한 바 있다.아울러 더타임스는 러시아군이 우크라이나에 대한 열압력탄 사용 정황들이 드러났고 우크라이나군이 해당 장비를 견인하는 사진 등이 나돌기도 했다고 전했다.이은정 (lejj@edaily.co.kr) 
--------------------------------------------------
한국 조선 쾌속 순항.. 1분기 수주 50% 쾌거


                        한국 조선업계가 해양 환경규제 강화에 힘입어 지난달 전 세계 선박 발주량의 절반 이상을 수주했다. ‘K조선’이 1분기 기

6일 밤 방송된 KBS2 '新가족관계증명서-갓파더'에서는 강주은이 가비와 함께 라치카 크루를 만나는 모습이 그려졌다.이날 가비는 엄마 주은 덕에 자신의 드림카에 타볼 수 있었다. 가비는 "엄마가 끄는 게 정말 멋있다고 생각한다"고 말했고, 차를 탄 후 엔진 소리에마저 감탄을 내뱉었다. 주은은 "엄마는 엔진 소리에 힐링받는다"고 말했다.이날 강주은은 딸 가비의 라치카 크루를 만나기로 했다. 주은은 라치카를 만나기 전에 선물을 사주기로 했고, 가장 필요한 건 음료수란 말에 음료수 100병을 사가자고 제안했다. 가비는 손 큰 엄마를 자꾸 말려야 했다. 라치카 멤버들은 강주은이 등장하자 저세상 텐션으로 그를 격하게 반겼다. 강주은은 "그 인사하는 모습이 많이 과하더라"며 "가비랑 크루 멤버들이랑 똑같더라"고 말했다. 이어 강주은은 "(가비처럼) 옷도 약간 거의 다 안 입은 상태고, 다 똑같더라"며 신기해 했다.[박새롬 스타투데이 객원기자]
--------------------------------------------------
'라디오스타' 고은아 "과거 장롱에 돈 보관.. 휴대 전화 요금도 직접 대리점으로"


                        '라디오스타' 고은아가 독특했던 돈 관리를 공개했다. 6일 방송된 MBC 예능프로그램 '라디오스타'에서는 박종복, 여에스더, 고은아, 슬리피와 함께하는 ‘구해줘! 머니...
                    

'라디오스타' 고은아가 독특했던 돈 관리를 공개했다. 6일 방송된 MBC 예능프로그램 '라디오스타'에서는 박종복, 여에스더, 고은아, 슬리피와 함께하는 ‘구해줘! 머니’ 특집으로 꾸며졌다.이날 고은아는 과거 돈 관리로 "저는 돈을 어릴 때 회사에서 정산을 해주면 은행 가서 뽑아서 장롱에 모았다"며 "보통은 은행에 맡겨두는데 어린 나이에 못 믿어서 장롱에다가 넣었다"고 밝혔다. 이어 "그런 걱정도 했다. 밖에를 못 나가겠더라. 나의 전 재산이 집에 있으니까. 의도치 않게 집순이가 됐다"며 "이제는 장롱에 안

[OSEN=김예솔 기자] KCM이 최환희와 제주도 여행을 떠났다. 6일에 방송된 KBS2TV ‘新가족관계증명서 갓파더’에서는 KCM과 최환희가 제주도로 여행을 떠나는 모습이 공개됐다. 이날 KCM은 제주도로 최환희를 이끌었다. 최환희는 "다른 건 몰라도 낚시는 안 했으면 좋겠다. 멀미가 너무 심하다"라고 이야기했다. KCM은 알겠다고 호언장담했지만 멀미약까지 준비해 낚싯배로 이끌었다. KCM은 친구를 만나 배 구경을 시켜주겠다며 최환희에게 구명조끼를 입히고 안으로 이끌었다. 최환희는 "배가 얼마냐"라는 질문에 KCM의 친구는 "5천만원"이라고 답했다. 이에 최환희는 "그 중에 창모형 돈은 얼마 들어갔나"라고 물었고 KCM은 다급하게 수습해 웃음을 자아냈다. 그 사이 KCM의 친구는 정박해 있던 배의 닻줄을 풀었다. 최환희는 그 모습을 보고 밖으로 빠져 나오려고 했지만 KCM이 이를 막아 최환희를 납치해 주위를 폭소케 했다. 최환희는 "나한테 너무 원망스러웠다. 한 두 번 당해본 게 아닌데"라고 말해 웃음을 자아냈다. 배가 출발해 바다로 나가자 돌고래가 있어 주위를 깜짝 놀라게 만들었다. 최환희는 제작진과의 인터뷰를 통해 "납치 당해서 우울해 있었는데 돌고래를 그렇게 가까이에서 본 건 처음"이라며 신기해했다. KCM은 "반은 먹고 들어갔다"라며 함께 신나했다. KCM은 낚시를 시작했다. 얼마 후 입질을 느낀 KCM은 신나서 소리를 질렀다. 최환희는 "반신반의 했다. 정말 잡힌건가 싶기도 하고 낚싯대 휜 게 장난 아니었다"라고 말했다. KCM은 부시리 한 마리를 낚아 기고만장했다. 잠시 후 KCM은 또 다시 히트라고 소리쳤다. KCM은 최환희에게 손맛을 느끼게 해주고 싶어 낚싯대를 넘겼고 최환희는 낚싯대를 감았다. KCM은 뜰채로 부시리를 낚았다. KCM은 "인증샷찍자"라며 최환희의 사진을 남겼다. 최환희는 "정말 신기했다"라고 말했다. KCM은 잡은 부시리를 갖고 가서 흑돼지와 물물교환했다. KCM은 "나는 회를 별로 안 좋아한다"라고 말했다. 하지만 최환희는 

[KBS 울산] [앵커]윤석열 대통령 당선인과 전국 시·도지사들이 오늘 대통령직 인수위원회에서 대선 이후 첫 간담회를 가졌습니다.이 자리에서 송철호 울산시장은 부유식 해상풍력 정부 지원과 부울경 광역급행철도 건설을 건의했습니다.공웅조 기자가 보도합니다.[리포트]대통령 선거 이후 처음 한 자리에 모인 윤석열 대통령 당선인과 전국의 시도지사들.윤 당선인은 모든 지역이 스스로 발전 동력을 찾을 수 있도록 재정 권한을 강화하고 지역에 특화된 산업을 집중적으로 지원하겠다고 밝혔습니다.[윤석열/대통령 당선인 : "균형발전은 발전의 속도를 동일하게 맞추는 것이 아니라 모든 지역에 기회를 균등하게 부여하는 것이고 대한민국 국민이 어디에 살든 간에 같은 공정한 기회를 누려야 한다는 (것을 의미합니다.)"]송철호 울산시장은 먼저 후보 시절 부유식 해상풍력 발전에 부정적인 인식을 보여온 당선인에게 시민 대상 토론회와 간담회를 열고 관내 어민단체와 상생 협약을 맺는 등, 해상풍력의 주민수용성 확보에 노력해왔다는 점을 강조했습니다.이와 함께 울산만의 사업이 아니라 당선인 공약인 부울경의 공동 발전을 위한 마중물이라며 정부 지원을 촉구했습니다.송 시장은 또 울산·부산·대구를 1시간 생활권으로 묶는 광역급행철도가 필요하다며 정부계획 반영과 예비타당성조사 면제 등을 요청했습니다.한편 송 시장은 간담회 참석에 앞서 인수위 지역균형발전특위를 찾아 수소모빌리티와 도심항공교통 클러스터 구축, 울산권 광역철도와 도시철도 건설 등 7개 과제를 추가로 건의했습니다.대통령직 인수위원회는 울산 등 각 지역공약 중 우선과제를 선정해 다음달 초 대통령 당선인에게 국정과제 최종안을 보고할 예정입니다.KBS 뉴스 공웅조입니다.촬영기자:김근영/그래픽:박서은공웅조 기자 (salt@kbs.co.kr)
--------------------------------------------------
고액 보수 논란에 부동산 의혹..한덕수 "청문회서 말씀드릴 것"


                        한덕수(사진) 국

 [이데일리 김성훈 기자] 아이돌그룹 방탄소년단(BTS)의 대통령 취임식 참석 여부를 놓고 대통령직인수위원회(인수위)와 취임준비위원회(취임위)가 다른 입장을 내며 오락가락한 모습을 보이고 있다. 인수위가 “BTS의 대통령 취임식 참석을 전혀 검토한 바 없다”고 공지한 지 2시간여 만에 취임위가 “확정된 사안은 아니다”는 입장을 내놓으며 혼선을 보이고 있어서다. 인수위와 취임위 측 커뮤니케이션이 혼선을 빚은 가운데 BTS 팬들은 정치적으로 이용하지 말라며 강도 높은 비판을 멈추지 않고 있다. 단순 헤프닝으로 일단락되나 싶었던 BTS 취임식 이슈는 인수위 공지가 나온 지 2시간 30분 만에 분위기가 달라졌다. 인수위 대변인실 공지 이후 취임위 대변인실이 별도 공지를 내고 “BTS 초청 공연을 논의 과정 중에 검토한 것은 사실이지만 아직 확정된 사안이 아니다”라고 밝혔다. 인수위와 취임위가 BTS 출연 여부를 놓고 다소 다른 뉘앙스의 입장을 번갈아 낸 셈이다. 업무 영역이 다른 인수위와 취임위라고 하지만 사전 조율이 이뤄지지 않았음을 인정하는 대목이다. 논란의 시작은 전날 KBS 라디오 ‘주진우 라이브’에 출연한 박주선 대통령취임준비위원장에서 비롯됐다. 박 위원장은 이날 ‘BTS가 취임식 공연을 준비 중인가’라는 진행자 질문에 “그것도 지금 논의하고 있다”고 답하면서 불씨를 키웠다. 박 위원장은 “너무 화려하면서도 또 내용은 빈약하고 그런 것보다는 외관보다는 내실이 있어야 한다는 (윤석열 당선인의) 말씀이 있었기 때문에 그런 방향으로 지금 취임식을 준비하고 있다”며 취임식 준비 상황을 전했다.대통령 취임식에 BTS가 참석할 수 있다는 소식이 나오자 팬들은 응원보다 우려의 목소리를 나타냈다. 6일 인수위 공식 홈페이지에는 BTS를 취임식에 부르지 말라는 글이 1400건 가까이 올라왔다. 팬들은 “BTS를 정치적으로 이용하지 말아달라”며 대통령 취임식 불참을 요구하고 있다. BTS 소속사인 하이브도 “(BTS의 축하공연 논의는) 회사도 기사를 통해 알았고 아직까지 공식

In [18]:
len(title_lst)

15

In [19]:
len(summary_lst)

15

In [20]:
len(news_lst)

15

### 자연어처리를 위한 데이터프레임 만들기

In [21]:
# 각 분야 뉴스 
economic_news = cate_news_lst[0]
entertain_news = cate_news_lst[1]
politics_news = cate_news_lst[2]

In [22]:
total_news = economic_news + entertain_news + politics_news

In [23]:
# 뉴스 각 15개씩
len(total_news)

45

In [24]:
# category 넣어주기: 리스트 더해주기
cate = ['eco']*15 + ['enter']*15 + ['politics']*15
cate

['eco',
 'eco',
 'eco',
 'eco',
 'eco',
 'eco',
 'eco',
 'eco',
 'eco',
 'eco',
 'eco',
 'eco',
 'eco',
 'eco',
 'eco',
 'enter',
 'enter',
 'enter',
 'enter',
 'enter',
 'enter',
 'enter',
 'enter',
 'enter',
 'enter',
 'enter',
 'enter',
 'enter',
 'enter',
 'enter',
 'politics',
 'politics',
 'politics',
 'politics',
 'politics',
 'politics',
 'politics',
 'politics',
 'politics',
 'politics',
 'politics',
 'politics',
 'politics',
 'politics',
 'politics']

In [25]:
# 데이터프레임

news_df = pd.DataFrame({'category': cate, 'news': total_news})
news_df

category                                               news
0        eco  최근 시멘트 공급 부족과 가격 급등이 이어지자 정부는 시멘트 업계 등과 함께 회의를...
1        eco   [뉴욕=이데일리 김정남 특파원] 미국 뉴욕 증시의 3대 지수가 6일(현지시간) 장...
2        eco  [KBS 울산]울산 동구는 울산시교육청과 업무협약을 맺고 남목초등학교 운동장 지하에...
3        eco  [KBS 울산]한국 조선업계가 올해 1분기 전세계에서 발주된 선박의 절반 이상을 수...
4        eco  [KBS 울산]울산과 부산 일대에 지정된 에너지산업융복합단지를 활성화하기 위한 추진...
5        eco  (뉴욕=연합뉴스) 윤영숙 연합인포맥스 특파원 = 뉴욕증시는 미국 연방준비제도(연준·...
6        eco  [뉴욕=이데일리 김정남 특파원] “기대인플레이션이 치솟을 수 있다는 점을 우려한다....
7        eco   [이데일리 이은정 기자] 러시아군이 우크라이나 민간인 시신을 이동식 화장시설로 화...
8        eco  [한국경제TV 신인규 기자]여기는 미국 동부시간 6일 오전 9시 31분입니다. 월가...
9        eco  LG전자가 6일부터 오는 6월 5일까지 부산 광안리에 위치한 ‘더 브릿지 호텔’에서...
10       eco   [이데일리 이은정 기자] 우크라이나군이 노획한 ‘진공폭탄’ 발사기로 러시아군을 공...
11       eco  한국 조선업계가 해양 환경규제 강화에 힘입어 지난달 전 세계 선박 발주량의 절반 이...
12       eco  카카오가 향후 5년간 3000억원을 들여 소상공인, 콘텐츠·예술 창작자, 모빌리티 ...
13       eco  #사례1. 지난달 8일 LG에너지솔루션의 사내 소통 채널 ‘엔톡’에는 한 여직원이 ...
14       eco  증선위는 반도체 기계 제조업체 프로텍 법인과 대표이사 및 담당임원을 검찰 통보하고 ...
15     enter   [뉴스엔 서유나 기자]고은아가 남동생 미르에게 받은 특별한 선물로 모발 이식을 꼽...
16     enter  [텐아시아=조준원 기자]그룹 아이브 멤버 장원영이 일상을 전했다.장원영이 6일 자신...
17     enter  6일 밤 방송된 KBS2 '新가족관계증명서-갓파더'에서는 강주은이 가비와 함께 라치...
18     enter  '라디오스타' 고은아가 독특했던 돈 관리를 공개했다. 6일 방송된 MBC 예능프로그...
19     enter  (엑스포츠뉴스 이정범 기자) 그룹 트레저(TREASURE)의 하루토는 5일 생일을 ...
20     enter  (서울=뉴스1) 박하나 기자 = 배우 고은아가 '라디오스타'에서 장롱에 돈을 보관한...
21     enter   (엑스포츠뉴스 이슬 기자) KCM이 최환희와 제주도 무전여행을 떠났다.6일 방송된...
22     enter  (엑스포츠뉴스 이이진 기자) '그린마더스클럽' 이요원이 추자현과 갈등을 빚었다.6일...
23     enter  슬리피가 결혼에 대해 언급했다. 6일 방송된 MBC 예능프로그램 ‘라디오스타’는 ‘...
24     enter  [스포츠경향] ‘라디오스타’ 여에스더가 회사 자랑에 나섰다.6일 오후 방송된 MBC...
25     enter  [OSEN=김수형 기자] ‘국민영수증’에서 위너의 강승윤과 김진우가 출연, 김진우는...
26     enter  방송인 겸 통역사 안현모의 사촌 고모로 잘 알려진 통역사 임종령이 놀라운 이력과 함...
27     enter  [OSEN=김예솔 기자] KCM이 최환희와 제주도 여행을 떠났다. 6일에 방송된 K...
28     enter  [스포츠투데이 최혜진 기자] '그린마더스클럽' 이요원과 추자현이 자녀 교육과 관련해...
29     enter  6일 첫 방송된 JTBC 새 수목드라마 '그린마더스클럽'에서는 이사온 이은표(이요원...
30  politics  [앵커] 북한이 선전 매체들을 총동원해 서욱 국방부 장관의 선제 타격 발언을 비판하...
31  politics  ■ 진행 : 오동건 앵커 ■ 출연 : 박창환 / 장안대 교수, 이종근 / 시사평론가...
32  politics  기사내용 요약 '美석유기업 수억원 월세 선금…이해충돌 가능성' 보도 한덕수 측 "계...
33  politics  [KBS 울산] [앵커]윤석열 대통령 당선인과 전국 시·도지사들이 오늘 대통령직 인...
34  politics   한덕수(사진) 국무총리 후보자가 로펌 및 대기업에서 고액 보수를 받은 것에 대한 ...
35  politics  박수현 청와대 국민소통수석이 6일 청와대 특수활동비가 문재인 대통령의 부인 김정숙 ...
36  politics  윤석열 대통령 당선인의 대통령취임준비위원회가 다음달 10일 열리는 제20대 대통령 ...
37  politics  탁 비서관은 이날 페이스북에 “(팩트는) 여사님이 샤넬에서 옷을 빌려 입은 뒤 반납...
38  politics  정부가 ‘포스트 오미크론’ 대응 체계를 공식 언급하고 나섰다. 사실상 ‘코로나 엔데...
39  politics  기사내용 요약 "바이든 방한, 국민에 비켜달라 못해…검토" "尹 최측근…초기부터 자...
40  politics   [이데일리 김성훈 기자] 아이돌그룹 방탄소년단(BTS)의 대통령 취임식 참석 여부...
41  politics  (워싱턴=뉴스1) 김현 특파원 = 웬디 셔먼 미 국무부 부장관은 6일(현지시간) 러...
42  politics  △김이순씨 별세, 박진호(국민의힘 윤리위원회 위원, 방위사업추진위원, 전 국회의원 ...
43  politics  리얼미터가 아시아경제 의뢰로 지난 4∼5일 서울 거주 유권자 1015명을 대상으로 ...
44  politics  박 수석은 6일 MBC ‘뉴스외전’에 출연해 “특활비는 법으로 공개하지 못하게 돼 ...

In [26]:
# news_df.to_csv('./data/daum_news.csv')

### clustering

#### clustering을 위한 전처리

In [28]:
from konlpy.tag import Hannanum, Komoran, Kkma

In [29]:
kor = Komoran()

In [30]:
docs = []
for news in news_df['news']:
    docs.append(news)

In [31]:
docs

["최근 시멘트 공급 부족과 가격 급등이 이어지자 정부는 시멘트 업계 등과 함께 회의를 열어 2분기부터 총력 생산 체제에 돌입하기로 했습니다. 이에따라 국내 7개 시멘트 회사는 전 분기보다 35% 이상 시멘트를 추가 생산하고, 수출 물량은 내수로 전환해 공급 불안을 해소할 계획입니다. 시멘트의 원료인 유연탄 가격 급등과 관련해선 러시아에 대한 수입 의존도를 줄여 일단 공급망을 안정화하기로 했습니다. 지금까지 유연탄은 러시아에서 75%, 호주에서 25%를 수입해왔으나 앞으로는 러시아 54%, 호주 46%로 비중을 조정하기로 했습니다. 하지만 유연탄 가격이 이미 지난해보다 2배가량 오른 상태라 레미콘 업계와 건설업계 간 이견 조정이 쉽지 않아 추가 논의가 불가피할 것으로 보입니다. YTN 박홍구 (hkpark@ytn.co.kr)※ '당신의 제보가 뉴스가 됩니다' [카카오톡] YTN 검색해 채널 추가 [전화] 02-398-8585 [메일] social@ytn.co.kr",
 ' [뉴욕=이데일리 김정남 특파원] 미국 뉴욕 증시의 3대 지수가 6일(현지시간) 장 초반 일제히 급락하고 있다. 연방준비제도(Fed)의 가파른 긴축 전망이 커지면서, 침체 우려가 고개를 들고 있기 때문이다.마켓포인트에 따르면 이날 미국 뉴욕증권거래소에서 블루칩을 모아놓은 다우존스 30 산업평균지수는 전거래일 대비 0.75% 하락하고 있다. 대형주 중심의 스탠더드앤드푸어스(S&P) 500 지수는 1.24% 내리고 있다. 기술주 중심의 나스닥 지수는 2.36% 떨어지고 있다. 이외에 중소형주 위주의 러셀 2000 지수는 1.54% 내리고 있다.월가 공포지수로 불리는 시카고옵션거래소 변동성 지수(VIX)는 16.21% 상승한 24.44를 기록하고 있다.뉴욕 증시가 주목하는 건 연준이다. 패트릭 하커 필라델피아 연방준비은행 총재는 이날 미국 델라웨어주 상공회의소에서 한 연설을 통해 “기대인플레이션이 치솟을 수 있다는 점을 우려한다”며 “한 해가 지나는 과정에서 체계적인 일련의 기준금리 인상을 예상한다

In [ ]:
# 텍스트 형식으로

#### KMeans

In [27]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=3)
kmeans.fit(news_df)

ValueError: could not convert string to float: 'eco'