In [122]:
import pandas as pd
import numpy as np
import datetime 
from datetime import datetime,timedelta

In [7]:
# 21. How to convert a series of date-strings to a timeseries?
# Difficiulty Level: L2 Input
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

# 0   2010-01-01 00:00:00
# 1   2011-02-02 00:00:00
# 2   2012-03-03 00:00:00
# 3   2013-04-04 00:00:00
# 4   2014-05-05 00:00:00
# 5   2015-06-06 12:20:00
# dtype: datetime64[ns]


In [12]:
#21. 문자형-> 시간형
ser.apply(lambda x: pd.to_datetime(x) )

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]

In [13]:
 #21. astype 은 사용못하나? 가능하다고 한다
ser.astype('datetime64')

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]

In [ ]:
# 22. How to get the day of month, week number, day of year and day of week from a series of date strings?
# Difficiulty Level: L2 Get the day of month, week number, day of year and day of week from ser. Input

ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

# Date:  [1, 2, 3, 4, 5, 6]
# Week number:  [53, 5, 9, 14, 19, 23]
# Day num of year:  [1, 33, 63, 94, 125, 157]
# Day of week:  ['Friday', 'Wednesday', 'Saturday', 'Thursday', 'Monday', 'Saturday']

In [26]:
#22.
print('Date: ',ser.astype('datetime64').dt.day.tolist())
print('Week number: ', ser.astype('datetime64').dt.weekofyear.tolist())
print('Day num of year: ', ser.astype('datetime64').dt.dayofyear.tolist())
print('Day of week: ', ser.astype('datetime64').dt.dayofweek.tolist())
print('Day of week: ', ser.astype('datetime64').dt.day_name().tolist())

Date:  [1, 2, 3, 4, 5, 6]
Week number:  [53, 5, 9, 14, 19, 23]
Day num of year:  [1, 33, 63, 94, 125, 157]
Day of week:  [4, 2, 5, 3, 0, 5]
Day of week:  ['Friday', 'Wednesday', 'Saturday', 'Thursday', 'Monday', 'Saturday']


C:\Users\21ckw\AppData\Local\Temp/ipykernel_10276/142173032.py:3: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated. Please use Series.dt.isocalendar().week instead.
  print('Week number: ', ser.astype('datetime64').dt.weekofyear.tolist())


In [59]:
# 23. How to convert year-month string to dates corresponding to the 4th day of the month?
# Difficiulty Level: L2 Change ser to dates that start with 4th of the respective months. Input

ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])

# Desired Output

# 0   2010-01-04
# 1   2011-02-04
# 2   2012-03-04
# dtype: datetime64[ns]

In [61]:
from dateutil.parser import parse

ser.apply(lambda x : pd.to_datetime(x))+ timedelta(days=3)

0   2010-01-04
1   2011-02-04
2   2012-03-04
dtype: datetime64[ns]

In [75]:
# 24. How to filter words that contain atleast 2 vowels from a series?
# Difficiulty Level: L3 From ser, extract words that contain atleast 2 vowels. Input

ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])

In [77]:
vowel =['a','e','i','o','u','A','E','I','O','U']

for word in ser:
    count = 0
    for i in range(len(word)):
        if word[i] in vowel:
            count+=1
        else:
            pass
    if count>=2:
        print(word)

Apple
Orange
Money


In [78]:
# Solution
from collections import Counter
mask = ser.apply(lambda x: sum([Counter(x.lower()).get(i, 0) for i in list('aeiou')]) >= 2)
ser[mask]

0     Apple
1    Orange
4     Money
dtype: object

In [ ]:
# 25. How to filter valid emails from a series?
# Difficiulty Level: L3 Extract the valid emails from the series emails. 
# The regex pattern for valid emails is provided as reference. Input

emails = pd.Series(['buying books at amazom.com', 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com'])
pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'

In [80]:
# 26. How to get the mean of a series grouped by another series?
# Difficiulty Level: L2 Compute the mean of weights of each fruit. Input

fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))
print(weights.tolist())
print(fruit.tolist())
#> [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
#> ['banana', 'carrot', 'apple', 'carrot', 'carrot', 'apple', 'banana', 'carrot', 'apple', 'carrot']

# # values can change due to randomness
# apple     6.0
# banana    4.0
# carrot    5.8
# dtype: float64

[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
['carrot', 'banana', 'banana', 'banana', 'banana', 'carrot', 'apple', 'carrot', 'carrot', 'banana']


In [81]:
weights.groupby(fruit).mean()

apple     7.0
banana    4.8
carrot    6.0
dtype: float64

In [83]:
# 27. How to compute the euclidean distance between two series?
# Difficiulty Level: L2 Compute the euclidean distance between series (points) p and q, without using a packaged formula. Input

p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])

In [86]:
sum((p-q)**2)**0.5

18.16590212458495

In [91]:
# 28. How to find all the local maxima (or peaks) in a numeric series?
# Difficiulty Level: L3 Get the positions of peaks (values surrounded by smaller values on both sides) in ser. Input

ser = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])

# array([1, 5, 7])

In [101]:
# np.diff(ser)
# np.sign(np.diff(ser)) # 부호변화 [ 1, -1,  1,  1,  1, -1,  1, -1]
# np.diff(np.sign(np.diff(ser))) # 부호 + -> - 찾고싶음
dd = np.diff(np.sign(np.diff(ser)))
peak_locs = np.where(dd==-2)[0]+1
peak_locs

array([1, 5, 7], dtype=int64)

In [102]:
# 29. How to replace missing spaces in a string with the least frequent character?
# Replace the spaces in my_str with the least frequent character. Difficiulty Level: L2 Input

my_str = 'dbc deb abed gade'

# Desired Output

# 'dbccdebcabedcgade'  # least frequent is 'c'

In [116]:
my_str
ser = pd.Series(list(my_str))
freq = ser.value_counts(ascending=True)
freq.index[0]
my_str.replace(' ',freq.index[0])

'dbccdebcabedcgade'

In [117]:
# 30. How to create a TimeSeries starting ‘2000-01-01' and 10 weekends (saturdays) after that having random numbers as values?
# Difficiulty Level: L2 Desired output

# values can be random
# 2000-01-01    4
# 2000-01-08    1
# 2000-01-15    8
# 2000-01-22    4
# 2000-01-29    4
# 2000-02-05    2
# 2000-02-12    4
# 2000-02-19    9
# 2000-02-26    6
# 2000-03-04    6

In [128]:
# 30. 어렵다
# pd.to_datetime('2000-01-01').strftime('%Y-%m-%d')
print(np.random.randint(1,10,10))
pd.date_range('2000-01-01',periods =10, freq= 'W-SAT')

[7 9 8 7 7 5 9 3 9 5]


DatetimeIndex(['2000-01-01', '2000-01-08', '2000-01-15', '2000-01-22',
               '2000-01-29', '2000-02-05', '2000-02-12', '2000-02-19',
               '2000-02-26', '2000-03-04'],
              dtype='datetime64[ns]', freq='W-SAT')

In [130]:
#  31. How to fill an intermittent time series so all missing dates show up with values of previous non-missing date?
# Difficiulty Level: L2 ser has missing dates and values. Make all missing dates appear and fill up with value from previous date.
# Input

ser = pd.Series([1,10,3,np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))
print(ser)
#> 2000-01-01     1.0
#> 2000-01-03    10.0
#> 2000-01-06     3.0
#> 2000-01-08     NaN
#> dtype: float64

# Desired Output

# 2000-01-01     1.0
# 2000-01-02     1.0
# 2000-01-03    10.0
# 2000-01-04    10.0
# 2000-01-05    10.0
# 2000-01-06     3.0
# 2000-01-07     3.0
# 2000-01-08     NaN

2000-01-01     1.0
2000-01-03    10.0
2000-01-06     3.0
2000-01-08     NaN
dtype: float64


In [138]:
#31. 연속날짜 채우기
ser.resample('D').ffill()


2000-01-01     1.0
2000-01-02     1.0
2000-01-03    10.0
2000-01-04    10.0
2000-01-05    10.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     NaN
Freq: D, dtype: float64

In [139]:
# 32. How to compute the autocorrelations of a numeric series?
# Difficiulty Level: L3 Compute autocorrelations for the first 10 lags of ser. Find out which lag has the largest correlation. 
# Input

ser = pd.Series(np.arange(20) + np.random.normal(1, 10, 20))

# Desired output

# values will change due to randomness
# [0.29999999999999999, -0.11, -0.17000000000000001, 0.46000000000000002, 0.28000000000000003, -0.040000000000000001, -0.37, 0.41999999999999998, 0.47999999999999998, 0.17999999999999999]
# Lag having highest correlation:  9

In [142]:
# 32. df[''].corr(),  df.corr
# [ser.autocorr(i).round(2) for i in range(11)]

In [151]:
# 33. How to import only every nth row from a csv file to create a dataframe?
# Difficiulty Level: L2 Import every 50th row of BostonHousing dataset as a dataframe.

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv')
df.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [166]:
# chunksize 한번에 읽어올 행 갯수

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv',chunksize=50)
df1 = pd.DataFrame() # 빈데이터 프레임 생성
for chunk in df:
    df1 = pd.concat([df1, chunk.iloc[0,:]],axis=1)
    
#     df1.append(chunk.iloc[0,:])  df1 이 방법은 미래에 없어질 수도 있다는 Future warning 뜸
df1.transpose()     
        


crim    zn  indus  chas    nox     rm    age     dis   rad    tax  \
0     0.00632  18.0   2.31   0.0  0.538  6.575   65.2  4.0900   1.0  296.0   
50    0.08873  21.0   5.64   0.0  0.439  5.963   45.7  6.8147   4.0  243.0   
100   0.14866   0.0   8.56   0.0  0.520  6.727   79.9  2.7778   5.0  384.0   
150   1.65660   0.0  19.58   0.0  0.871  6.122   97.3  1.6180   5.0  403.0   
200   0.01778  95.0   1.47   0.0  0.403  7.135   13.9  7.6534   3.0  402.0   
250   0.14030  22.0   5.86   0.0  0.431  6.487   13.0  7.3967   7.0  330.0   
300   0.04417  70.0   2.24   0.0  0.400  6.871   47.4  7.8278   5.0  358.0   
350   0.06211  40.0   1.25   0.0  0.429  6.490   44.4  8.7921   1.0  335.0   
400  25.04610   0.0  18.10   0.0  0.693  5.987  100.0  1.5888  24.0  666.0   
450   6.71772   0.0  18.10   0.0  0.713  6.749   92.6  2.3236  24.0  666.0   
500   0.22438   0.0   9.69   0.0  0.585  6.027   79.7  2.4982   6.0  391.0   

     ptratio       b  lstat  medv  
0       15.3  396.90   4.98  24.0  
50      16.8  395.56  13.45  19.7  
100     20.9  394.76   9.42  27.5  
150     14.7  372.80  14.10  21.5  
200     17.0  384.30   4.45  32.9  
250     19.1  396.28   5.90  24.4  
300     14.8  390.86   6.07  24.8  
350     19.7  396.90   5.98  22.9  
400     20.2  396.90  26.77   5.6  
450     20.2    0.32  17.44  13.4  
500     19.2  396.90  14.33  16.8